this.localisation_fr = {
    label_previous:"Précédent",
    label_current:"Actuel",
    label_global:"Score",
    label_firstname:"Prénom",
    label_name:"Nom",
    label_print:"Imprimer",
    label_restart:"Recommencer",
    label_certificate_desc:"CERTIFICAT DE VALIDATION DE LA FORMATION.",
    label_certificate_title:"TITRE:",
    label_certificate_content:"CONTENU DE LA FORMATION:",
    label_certificate_duration:"DURÉE ESTIMÉE:",
    label_certificate_result:"RESULTAT FINAL:",
    label_certificate_objectives:"OBJECTIFS:",
    dateFormat:"dd/MM/yyyy",
    tab: "Onglet",
    lbl_prev: "Précédent",
    lbl_next: "Suivant",
    aria_controles_diapo:"Contrôles du carrousel",
    aria_prev:"Diapo précédente",
    aria_next:"Diapo suivante",
    noAltText: "Emplacement du texte alternatif de l'image",
    noscore: "vous avez terminé",
    label_points: "points",
    min: "min",
    sec: "sec",
    label_previous_score: "Score précédent"
};
this.localisation_en = {
    label_previous:"Previous",
    label_current:"Current",
    label_global:"Score",
    label_firstname:"Firstname",
    label_name:"Name",
    label_print:"Print",
    label_restart:"Restart",
    label_certificate_desc:"COURSE CERTIFICATE.",
    label_certificate_title:"TITLE:",
    label_certificate_content:"CONTENT:",
    label_certificate_duration:"DURATION:",
    label_certificate_result:"FINAL RESULT:",
    label_certificate_objectives:"OBJECTIVES:",
    dateFormat:"MM/dd/yyyy",
    noscore: "you're done",
    label_points: "points",
    min: "min",
    sec: "sec",
    label_previous_score: "Previous score"
};
this.localisation_es = {
    label_previous:"Anterior",
    label_current:"Actual",
    label_global:"Puntuación",
    label_firstname:"Nombre",
    label_name:"Apellido",
    label_print:"Impresión",
    label_restart:"Reintentar",
    label_certificate_desc:"CERTIFICADO DE VALIDATIÓN DE LA FORMACIÓN.",
    label_certificate_title:"TÍTULO:",
    label_certificate_content:"CONTENIDO DE FORMACIÓN:",
    label_certificate_duration:"DURACIÓN ESTIMADA:",
    label_certificate_result:"RESULTADO FINAL:",
    label_certificate_objectives:"OBJETIVOS:",
    dateFormat:"dd/MM/yyyy",
    noscore: "has terminado",
    label_points: "puntos",
    min: "min",
    sec: "sec",
    label_previous_score: "Puntuación anterior"
};
this.localisation_nl = {
    label_previous:"Vorig",
    label_current:"Stroom",
    label_global:"Partituur",
    label_firstname:"Voornaam",
    label_name:"Naam",
    label_print:"Printen",
    label_restart:"Opnieuw beginnen",
    label_certificate_desc:"CERTIFICAAT VAN VALIDERING VAN OPLEIDING.",
    label_certificate_title:"TITEL:",
    label_certificate_content:"INHOUD VAN DE OPLEIDING:",
    label_certificate_duration:"GESCHATTE TIJD:",
    label_certificate_result:"EINDRESULTAAT:",
    label_certificate_objectives:"DOELSTELLINGEN:",
    dateFormat:"dd/MM/yyyy",
    tab: "Tab",
    lbl_prev: "Vorig",
    lbl_next: "Volgend",
    aria_controles_diapo:"Carrouselbedieningen",
    aria_prev:"Vorige dia",
    aria_next:"Volgende dia",
    noAltText: "Locatie voor de alternatieve tekst van de afbeelding",
    noscore: "je bent klaar",
    label_points: "punten",
    min: "min",
    sec: "sec",
    label_previous_score: "Vorige score"
};
this.localisation_de = {
    label_previous:"Früher",
    label_current:"Aktuelle",
    label_global:"Score",
    label_firstname:"Vorname",
    label_name:"Name",
    label_print:"Drucken",
    label_restart:"Neu starten",
    label_certificate_desc:"BESCHEINIGUNG DER BEWERTUNG DER AUSBILDUNG.",
    label_certificate_title:"TITEL:",
    label_certificate_content:"SCHULUNGSINHALT:",
    label_certificate_duration:"GESCHÄTZTE ZEIT:",
    label_certificate_result:"ENDGÜLTIGE ERGEBNISSE:",
    label_certificate_objectives:"ZIELE:",
    dateFormat:"dd/MM/yyyy",
    tab: "Tab",
    lbl_prev: "Zurück",
    lbl_next: "Weiter",
    aria_controles_diapo:"Karussellsteuerungen",
    aria_prev:"Vorherige Folie",
    aria_next:"Nächste Folie",
    noAltText: "Alternativer Textort des Bildes",
    noscore: "du bist fertig",
    label_points: "Punkte",
    min: "min",
    sec: "sec",
    label_previous_score: "Vorherige Punktzahl"
};
this.localisation_it = {
    label_previous:"Precedente",
    label_current:"Corrente",
    label_global:"Punteggio",
    label_firstname:"Cognome",
    label_name:"Nome",
    label_print:"Stampa",
    label_restart:"Riavviare",
    label_certificate_desc:"CERTIFICATO DI CONVALIDA DELLA FORMAZIONE.",
    label_certificate_title:"TITOLO:",
    label_certificate_content:"CONTENUTO DELLA FORMAZIONE:",
    label_certificate_duration:"TEMPO STIMATO:",
    label_certificate_result:"RISULTATO FINALE:",
    label_certificate_objectives:"OBIETTIVI:",
    dateFormat:"dd/MM/yyyy",
    tab: "Tab",
    lbl_prev: "Precedente",
    lbl_next: "Seguente",
    aria_controles_diapo:"Controlli del carosello",
    aria_prev:"Precedente slide",
    aria_next:"Prossima slide",
    noAltText: "Posizione del testo alternativa dell'immagine",
    noscore: "hai finito",
    label_points: "punti",
    min: "min",
    sec: "sec",
    label_previous_score: "Punteggio precedente"
};
this.localisation_zh = {
    label_previous:"上一页",
    label_current:"电流",
    label_global:"得分",
    label_firstname:"名字",
    label_name:"名",
    label_print:"打印",
    label_restart:"重新启动",
    label_certificate_desc:"培训验证证书。",
    label_certificate_title:"标题:",
    label_certificate_content:"培训内容:",
    label_certificate_duration:"估计时间:",
    label_certificate_result:"最终结果:",
    label_certificate_objectives:"目标:",
    dateFormat:"dd/MM/yyyy",
    tab: "标签",
    lbl_prev: "上一页",
    lbl_next: "下一步",
    aria_controles_diapo:"轮播控件",
    aria_prev:"上一张幻灯片",
    aria_next:"下一张幻灯片",
    noAltText: "图像的替代文本位置",
    noscore:"你已经完成了",
    label_points: "点数",
    min: "min",
    sec: "sec",
    label_previous_score: "先前分数"
};
this.localisation_pt = {
    label_previous:"Anterior",
    label_current:"Atual",
    label_global:"Pontuação",
    label_firstname:"Primeiro nome",
    label_name:"Nome",
    label_print:"Impressão",
    label_restart:"Reinicie",
    label_certificate_desc:"CERTIFICADO DE VALIDAÇÃO DO TREINAMENTO.",
    label_certificate_title:"TÍTULO:",
    label_certificate_content:"CONTEÚDO DO TREINAMENTO:",
    label_certificate_duration:"TEMPO ESTIMADO:",
    label_certificate_result:"RESULTADO FINAL:",
    label_certificate_objectives:"OBJETIVOS:",
    dateFormat:"dd/MM/yyyy",
    tab: "Tab",
    lbl_prev: "Anterior",
    lbl_next: "Avançar",
    aria_controles_diapo:"Controles de carrossel",
    aria_prev:"Slide anterior",
    aria_next:"Próximo slide",
    noAltText: "Localização alternativa de texto da imagem",
    noscore: "você terminou",
    label_points: "pontos",
    min: "min",
    sec: "sec",
    label_previous_score: "Pontuação anterior"
};
this.localisation_tr = {
    label_previous:"Önceki",
    label_current:"Güncel",
    label_global:"Puan",
    label_firstname:"Adı",
    label_name:"Soyadı",
    label_print:"Baskı",
    label_restart:"Yeniden başlatın",
    label_certificate_desc:"EĞİTİMİN DEĞERLENDİRİLMESİ BELGESİ.",
    label_certificate_title:"BAŞLIK:",
    label_certificate_content:"EĞİTİM İÇERİĞİ:",
    label_certificate_duration:"BELIRTILEN ZAMAN:",
    label_certificate_result:"NİHAİ SONUÇ:",
    label_certificate_objectives:"HEDEFLER:",
    dateFormat:"dd/MM/yyyy",
    tab: "Sekme",
    lbl_prev: "Önceki",
    lbl_next: "Sonraki",
    aria_controles_diapo:"Carousel kontrolleri",
    aria_prev:"Önceki slayt",
    aria_next:"Bir sonraki slayt",
    noAltText: "Resmin alternatif metin konumu",
    noscore: "bitti",
    label_points: "makas",
    min: "min",
    sec: "sec",
    label_previous_score: "Önceki skor"
};
this.localisation_el = {
    label_previous:"Προηγούμενες",
    label_current:"Η τρέχουσα",
    label_global:"Σκορ",
    label_firstname:"Όνομα",
    label_name:"Επώνυμο",
    label_print:"Εκτύπωση",
    label_restart:"Κάντε επανεκκίνηση",
    label_certificate_desc:"ΠΙΣΤΟΠΟΙΗΤΙΚΟ ΕΠΙΚΥΡΩΣΗΣ ΤΗΣ ΕΚΠΑΙΔΕΥΣΗΣ.",
    label_certificate_title:"ΤΙΤΛΟΣ:",
    label_certificate_content:"ΠΕΡΙΕΧΟΜΕΝΟ ΤΗΣ ΕΚΠΑΙΔΕΥΣΗΣ:",
    label_certificate_duration:"ΕΚΤΙΜΩΜΕΝΟΣ ΧΡΟΝΟΣ:",
    label_certificate_result:"ΤΕΛΙΚΟ ΑΠΟΤΕΛΕΣΜΑ:",
    label_certificate_objectives:"ΣΤΟΧΟΙ:",
    dateFormat:"dd/MM/yyyy",
    tab: "Καρτέλα",
    lbl_prev: "Προηγούμενες",
    lbl_next: "Επόμενο",
    aria_controles_diapo:"Έλεγχοι καρουσέλ",
    aria_prev:"Προηγούμενη διαφάνεια",
    aria_next:"Επόμενη διαφάνεια.",
    noAltText: "Εναλλακτική θέση κειμένου της εικόνας",
    noscore: "έχετε τελειώσει",
    label_points: "σημεία",
    min: "min",
    sec: "sec",
    label_previous_score: "Προηγούμενη βαθμολογία"
};
this.localisation_ar = {
    label_previous:"سابق",
    label_current:"الحالية",
    label_global:"نتيجة",
    label_firstname:"الأسم الأول",
    label_name:"اسم",
    label_print:"طباعة",
    label_restart:"البدء من جديد",
    label_certificate_desc:"شهادة التحقق من التدريب.",
    label_certificate_title:":العنوان",
    label_certificate_content:"محتوى التدريب:",
    label_certificate_duration:"الوقت المقدر:",
    label_certificate_result:"نتيجة نهائية:",
    label_certificate_objectives:"الأهداف:",
    dateFormat:"dd/MM/yyyy",
    tab: "التبويب",
    lbl_prev: "سابق",
    lbl_next: "التالي",
    aria_controles_diapo:"ضوابط دائري",
    aria_prev:"الشريحة السابقة",
    aria_next:"الشريحة التالية",
    noAltText: "موقع النص البديل للصورة",
    noscore:"هل أنهيت",
    label_points: "نقاط",
    min: "min",
    sec: "sec",
    label_previous_score: "النتيجة السابقة"
};
this.localisation_he = {
    label_previous: "הקודם",
    label_current: "נוכחי",
    label_global: "ציון",
    label_firstname: "שם פרטי",
    label_name: "שם",
    label_print: "הדפס",
    label_restart: "הפעל מחדש",
    label_certificate_desc: "COURSE CERTIFICATE.",
    label_certificate_title: "TITLE:",
    label_certificate_content: "CONTENT:",
    label_certificate_duration: "DURATION:",
    label_certificate_result: "תוצאות סופיות:",
    label_certificate_objectives: "יעדים:",
    dateFormat: "MM / dd / yyyy",
    noscore: "סיימת",
    label_points: "נקודות",
    min: "דקות",
    sec: "שניות",
    label_previous_score: "ניקוד קודם"
};
this.localisation_ru = {
    label_previous:"предыдущий",
    label_current:"Текущий",
    label_global:"Гол",
    label_firstname:"Имя",
    label_name:"название",
    label_print:"Распечатать",
    label_restart:"Начать сначала",
    label_certificate_desc:"СЕРТИФИКАТ КУРСА.",
    label_certificate_title:"ЗАГЛАВИЕ:",
    label_certificate_content:"СОДЕРЖАНИЕ:",
    label_certificate_duration:"ПРОДОЛЖИТЕЛЬНОСТЬ:",
    label_certificate_result:"КОНЕЧНЫЙ РЕЗУЛЬТАТ:",
    label_certificate_objectives:"ЦЕЛИ:",
    dateFormat:"MM/dd/yyyy",
    noscore: "ты сделал",
    label_points: "точки",
    min: "минут",
    sec: "secondes",
    label_previous_score: "Предыдущая оценка"
};
this.localisation_sk = {
    label_previous:"predchádzajúca",
    label_current:"prúd",
    label_global:"skóre",
    label_firstname:"Krstné meno",
    label_name:"názov",
    label_print:"vytlačiť",
    label_restart:"Reštart",
    label_certificate_desc:"CERTIFIKÁT KURZU.",
    label_certificate_title:"HLAVA:",
    label_certificate_content:"OBSAH:",
    label_certificate_duration:"DOBA:",
    label_certificate_result:"ZÁVEREČNÝ VÝSLEDOK:",
    label_certificate_objectives:"CIELE:",
    dateFormat:"MM/dd/yyyy",
    noscore: "ste hotoví",
    label_points: "body",
    min: "minúty",
    sec: "sekundy",
    label_previous_score: "Predchádzajúce skóre"
};