this.localisation_fr = {
	audioPlayer:"Lecteur audio",
	audioPlayer_play:"Lecture",
	audioPlayer_pause:"Pause",
	audioPlayer_seek:"Barre de recherche",
	audioPlayer_mute:"Désactiver le son",
	audioPlayer_unmute:"Activer le son",
	sendingDataToLMS: "L'enregistrement de votre progression est en cours.",
  	doNotCloseThisWindow: "Ne fermez pas cette fenêtre pour ne pas perdre vos données.",
  	label_consigne_completionlibre: "Saisissez vos réponses dans les espaces à remplir, puis cliquez sur le bouton Valider.",
	label_consigne_completionlibre_fallback: "Saisissez vos réponses dans les espaces à remplir, puis cliquez sur le bouton Valider.",
	label_consigne_choice: "Sélectionnez la ou les bonnes réponses, puis cliquez sur le bouton Valider.",
	label_consigne_choice_fallback: "Sélectionnez la ou les bonnes réponses, puis cliquez sur le bouton Valider.",
	label_consigne_classification: "Faites glisser les vignettes dans les bons emplacements, puis cliquez sur le bouton Valider.",
	label_consigne_classification_fallback: "Pour chaque catégorie, sélectionnez la ou les bonnes réponses, puis cliquez sur le bouton Valider.",
	label_consigne_association: "Reliez les bonnes paires en cliquant sur les propositions, puis cliquez sur le bouton Valider.",
	label_consigne_association_fallback: "Pour chaque proposition, sélectionnez la bonne réponse dans la liste déroulante, puis cliquez sur le bouton Valider.",
	label_consigne_cercle: "Entourez d'un seul cercle, la ou les bonnes réponses, puis cliquez sur le bouton Valider.",
	label_consigne_cercle_fallback: "Sélectionnez la ou les bonnes réponses parmi les choix suivants, puis cliquez sur le bouton Valider.",
	label_consigne_derouler: "Sélectionnez la bonne réponse, puis cliquez sur le bouton Valider.",
	label_consigne_derouler_fallback: "Sélectionnez la bonne réponse, puis cliquez sur le bouton Valider.",
	label_consigne_flip_fallback: "Cliquez sur tous les éléments pour en voir le contenu.",
	label_consigne_truefalse: "Pour chaque affirmation, déterminez si elle est vraie ou fausse.",
	label_consigne_truefalse_fallback: "Pour chaque affirmation, déterminez si elle est vraie ou fausse.",
	label_restart: "Recommencer",
	label_instructions: "Consigne",
	label_validate:"Valider",
	label__restart:"Recommencer",
	label_solution:"Voir la solution",
	label_my_answers:"Mes réponses",
	label_feedback:"Feedback",
	label_back_to_activity:"Retour feedback",
	label_folder:"Ressources",
	label_summary:"Sommaire",
	label_sono:"Ce contenu est sonorisé. Activez le son et appuyez sur Commencer.",
    label_start:"Commencer",
    label_analyse:"Analyse de votre progression en cours, Veuillez patienter... ",
	label_rgaa_contrast:"Contraste élevé",
	label_rgaa_accessible:"Version accessible",
	label_progress:"Progression : ",
    aria_summary:"Ouvrir le sommaire",
    aria_resources:"Ouvrir les ressources",
    aria_close_summary:"Fermer le sommaire",
    aria_close_resources:"Fermer les ressources",
    aria_rgaa_contrast:"Afficher les couleurs contrastées",
    aria_rgaa_contrast_normal:"Afficher les couleurs standard",
    aria_rgaa_accessible:"Changer pour le mode accessible",
    aria_rgaa_normal:"Changer pour le mode standard",
    aria_rgaa_next:"Suivant",
    aria_rgaa_prev:"Précédent",
	message_connection_lms:"Connexion au tracker en cours...",
	message_connection_lms_unknown:"Version du LMS inconnue.",
	message_lms_error_0:"Impossible de trouver la fenêtre du LMS...",
	message_lms_error_1:"Impossible d'initialiser le tracker LMS...",
	message_lms_error_2:"Impossible d'initialiser le tracker LMS...",
	message_lms_error_3:"Erreur pendant la communication avec le tracker. La session ne sera pas enregistrée !",
	message_lms_error_4:"Taille de stockage pour les messages SCORM 1.2 atteinte, impossible de stocker des informations supplémentaires",
	message_lms_error_5_syfadis:"Erreur durant l'envoi de vos données, le serveur n'est pas accessible.",
	message_no_lms:"Impossible de détecter le LMS, votre progression ne sera pas sauvegardée, voulez-vous poursuivre la formation ?",
	timer_nopoint: "Vous ne remportez pas de points.",
	timer_points: "Vous remportez $$ point(s). ",
	timer_partial: "Vous remportez $$ point(s), ce qui n'est pas assez pour valider la question.",
	timer_instructions: "Vous avez $$ secondes pour répondre et valider.",
	score_final: "$1/$2 points",
	label_try: "dernier essai",
	label_tries: "essais restants",
	label_toast_forced_navigation_go_to_page: "Accéder à la page",
	label_toast_forced_navigation_info_header: "Vous n'avez pas vu tous les éléments de la page courante.",
	label_toast_forced_navigation_info_body: "Voulez-vous quand même passer à la page suivante ?",
	label_toast_forced_navigation_warning_header: "Des éléments n'ont pas été consultés.",
	label_toast_forced_navigation_warning_body: "Vous devez avoir consultés tous les éléments de la page pour pouvoir accéder à la page suivante.",
	label_toast_forced_navigation_go_to_next_page: "Page suivante",
	label_toast_forced_navigation_stay_on_page: "Page courante",
	btn_back_reponses: "Mes réponses",
	btn_retry_quizz: "Recommencer",
	label_lastattempt:"Dernière tentative",
	label_attempts:"tentatives restantes",
	choice_correct: "Correct",
	choice_incorrect: "Incorrect",
	choice_forgotten: "Oublié",
	accessibility_btn_summary_title: "Sommaire",
	accessibility_btn_summary_label: "Afficher le sommaire",
	accessibility_btn_resources_title: "Ressources complémentaires",
	accessibility_btn_resources_label:"Afficher les ressources",
	accessibility_progressBar_title: "Barre de progression",
	accessibility_actionButtons_label: "Boutons d'action",
	accessibility_sidebar_label:"Menu de navigation",
	accessibility_legendAndFeedback_label:"Légende et feedback",
	accessibility_legendAndFeedback_btn_label:"Agrandir ou rétrécir la légende et le feedback",
	accessibility_limitedTimeActivity_label:"Activité en temps limité",
	accessibility_successStatus_label:"Statut de réussite",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Réponse correcte",
	accessibility_activity_item_label_incorrect: "Réponse incorrecte",
	accessibility_activity_item_label_forgotten: "Réponse oubliée",
	accessibility_activity_item_label_correction: "Correction",
};
this.localisation_en = {
	audioPlayer:"Audio player",
	audioPlayer_play:"Play",
	audioPlayer_pause:"Pause",
	audioPlayer_seek:"Seekbar",
	audioPlayer_mute:"Mute",
	audioPlayer_unmute:"Unmute",
	sendDataToLMS: "Saving your progress is in progress.",
	doNotCloseThisWindow: "Do not close this window to avoid losing your data.",
	label_consigne_completionlibre: "Enter your answers in the spaces to be filled in, then click on the Validate button.",
	label_consigne_completionlibre_fallback: "Enter your answers in the spaces to be filled in, then click on the Validate button.",
	label_consigne_choice: "Select the correct answer(s), then click on the Validate button.",
	label_consigne_choice_fallback: "Select the correct answer(s), then click on the Validate button.",
	label_consigne_classification: "Drag the thumbnails into the correct locations, then click on the Validate button.",
	label_consigne_classification_fallback: "For each category, select the correct answer(s), then click on the Validate button.",
	label_consigne_association: "Connect the good pairs by clicking on the propositions, then click on the Validate button.",
	label_consigne_association_fallback: "For each proposal, select the correct answer from the drop-down list, then click on the Validate button.",
	label_consigne_cercle: "Place a single circle around the correct answer(s), then click on the Validate button.",
	label_consigne_cercle_fallback: "Select the correct answer(s) from the following choices, then click on the Validate button.",
	label_consigne_derouler: "Select the correct answer, then click on the Validate button.",
	label_consigne_derouler_fallback: "Select the correct answer, then click on the Validate button.",
	label_consigne_flip_fallback: "Click on all the elements to see their content.",
	label_consigne_truefalse: "For each statement, determine if it is true or false.",
	label_consigne_truefalse_fallback: "For each statement, determine if it is true or false.",
	label_restart: "Retry",
	label_instructions: "Instructions",
	label_validate:"Validate",
	label__restart:"Restart",
	label_solution:"See the solution",
	label_my_answers:"My answers",
	label_feedback:"Feedback",
	label_back_to_activity:"Back to activity",
	label_folder:"Resources",
	label_summary:"Summary",
    label_sono:"This content has sound or voices. Please turn on your speakers an click on Start. ",
	label_start: "Start",
    label_analyse:"Analysis of your progress, Please wait...",
    label_rgaa_contrast:"High contrast",

    label_rgaa_accessible:"Accessible version",
    label_progress:"Progress : ",
    aria_summary:"Open summary",
    aria_resources:"Open resources",
    aria_close_summary:"Close summary",
    aria_close_resources:"Close resources",
    aria_rgaa_contrast:"Switch to contrasted colors",
    aria_rgaa_contrast_normal:"Switch to classic colors",
    aria_rgaa_accessible:"Switch to accessible mode",
    aria_rgaa_normal:"Switch to standard mode",
    aria_rgaa_next:"Next",
    aria_rgaa_prev:"Previous",
	message_connection_lms:"Connecting to the LMS...",
	message_connection_lms_unknown:"Unknown LMS version.",
	message_lms_error_0:"Unable to find the LMS window...",
	message_lms_error_1:"Unable to initialise the LMS...",
	message_lms_error_2:"Unable to initialise the LMS...",
	message_lms_error_3:"Error while sending data to the LMS. Your session will not be saved.",
	message_lms_error_4:"Size of storage for messages SCORM 1.2 reached, impossible to store additional information",
    message_lms_error_5_syfadis:"Error while sending your data. The server can't be reached.",
    message_no_lms:"Unable to detect the LMS, your progression won't be saved, would you continue ?",
	timer_nopoint: "You do not earn any points.",
	timer_points: "You win $$ point(s).",
	timer_partial: "You earn $$ points, which is not enough to validate the question.",
	timer_instructions: "You have $$ seconds to answer and validate.",
	score_final: "$1/$2 points",
	label_try: "last try",
	label_tries: "remaining tries",
	label_toast_forced_navigation_go_to_page: "Go to the page",
	label_toast_forced_navigation_info_header: "You have not seen all the elements of the current page.",
	label_toast_forced_navigation_info_body: "Do you still want to go to the next page?",
	label_toast_forced_navigation_warning_header: "Items were not consulted.",
	label_toast_forced_navigation_warning_body: "You must have consulted all the elements of the page to be able to reach the following page.",
	label_toast_forced_navigation_go_to_next_page: "Next page",
	label_toast_forced_navigation_stay_on_page: "Current page",
	btn_back_reponses: "My answers",
	btn_retry_quizz: "Restart",
	label_lastattempt:"Last attempt",
	label_attempts:"remaining attempts",
	choice_correct: "Correct",
	choice_incorrect: "Incorrect",
	choice_forgotten: "Forgotten",
	accessibility_btn_summary_title: "Summary",
	accessibility_btn_summary_label: "Show summary",
	accessibility_btn_resources_title: "Additional resources",
	accessibility_btn_resources_label:"View resources",
	accessibility_progressBar_title: "Progressbar",
	accessibility_actionButtons_label: "Action buttons",
	accessibility_sidebar_label:"Navigation menu",
	accessibility_legendAndFeedback_label:"Legend and feedback",
	accessibility_legendAndFeedback_btn_label:"Expand or shrink legend and feedback",
	accessibility_limitedTimeActivity_label:"Limited time activity",
	accessibility_successStatus_label:"Success status",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Correct answer",
	accessibility_activity_item_label_incorrect: "Incorrect answer",
	accessibility_activity_item_label_forgotten: "Forgotten response",
	accessibility_activity_item_label_correction: "Correction",
};
this.localisation_es = {
	audioPlayer:"Reproductor de música",
	audioPlayer_play:"Tocar",
	audioPlayer_pause:"Pausa",
	audioPlayer_seek:"Barra de busqueda",
	audioPlayer_mute:"Mudo",
	audioPlayer_unmute:"Activar sonido",
	sendDataToLMS: "La grabación de su progreso está en curso.",
	doNotCloseThisWindow: "No cierre esta ventana para evitar perder sus datos.",
	label_consigne_completionlibre: "Ingrese sus respuestas en los espacios a completar, luego haga clic en el botón Validar.",
	label_consigne_completionlibre_fallback: "Ingrese sus respuestas en los espacios a completar, luego haga clic en el botón Validar.",
	label_consigne_choice: "Seleccione la (s) respuesta (s) correcta (s), luego haga clic en el botón Validar.",
	label_consigne_choice_fallback: "Seleccione la (s) respuesta (s) correcta (s), luego haga clic en el botón Validar.",
	label_consigne_classification: "Arrastre las miniaturas a las ubicaciones correctas, luego haga clic en el botón Validar.",
	label_consigne_classification_fallback: "Para cada categoría, seleccione la (s) respuesta (s) correcta (s), luego haga clic en el botón Validar.",
	label_consigne_association: "Conecte los buenos pares haciendo clic en las proposiciones, luego haga clic en el botón Validar.",
	label_consigne_association_fallback: "Para cada propuesta, seleccione la respuesta correcta de la lista desplegable, luego haga clic en el botón Validar.",
	label_consigne_cercle: "Coloque un solo círculo alrededor de las respuestas correctas, luego haga clic en el botón Validar.",
	label_consigne_cercle_fallback: "Seleccione las respuestas correctas de las siguientes opciones, luego haga clic en el botón Validar.",
	label_consigne_derouler: "Seleccione la respuesta correcta, luego haga clic en el botón Validar.",
	label_consigne_derouler_fallback: "Seleccione la respuesta correcta, luego haga clic en el botón Validar.",
	label_consigne_flip_fallback: "Haz clic en todos los elementos para ver su contenido",
	label_consigne_truefalse: "Para cada afirmación, determine si es verdadera o falsa.",
	label_consigne_truefalse_fallback: "Para cada afirmación, determine si es verdadera o falsa.",
	label_restart: "Reiniciar",
	label_instructions: "Instrucciones",
	label_validate:"Validar",
	label__restart:"Reiniciar",
	label_solution:"Ver la solución",
	label_my_answers:"Mis respuestas",
	label_feedback:"Realimentación",
	label_back_to_activity:"Volver a la actividad",
	label_folder:"Recursos",
	label_summary:"Resumen",
    label_sono:"Este contenido está cableado para el sonido. Activar el sonido y pulse Iniciar.",
	label_start:"Iniciar",
    label_analyse:"Análisis de su progreso, Espere... ",
    label_rgaa_contrast:"Alto contraste",
    label_rgaa_accessible:"Versión accesible",
    label_progress:"Progreso : ",
    aria_summary:"Abre el resumen",
    aria_resources:"Abrir recursos",
    aria_close_summary:"Cerrar el resumen",
    aria_close_resources:"Cerrar recursos",
    aria_rgaa_contrast:"Modo de color accesible",
    aria_rgaa_contrast_normal:"Modo de color estándar",
    aria_rgaa_accessible:"Modo accesible",
    aria_rgaa_normal:"Modo estándar",
    aria_rgaa_next:"Próximo",
    aria_rgaa_prev:"Anterior",
	message_connection_lms:"Conexión con el LMS ...",
	message_connection_lms_unknown:"Versión desconocida LMS.",
	message_lms_error_0:"No se puede encontrar la ventana LMS ...",
	message_lms_error_1:"No se puede inicializar el LMS ...",
	message_lms_error_2:"No se puede inicializar el LMS ...",
	message_lms_error_3:"Error al enviar datos al LMS. no se guardará su sesión.",
	message_lms_error_4:"No se puede detectar LMS. no se guardará su progreso. va a continuar con el entrenamiento?",
    message_lms_error_5_syfadis:"Error al enviar sus datos, el servidor no es accesible.",
    message_no_lms:"No se puede detectar LMS, no se guardará su progreso, va a continuar con el entrenamiento?",
	timer_nopoint: "Usted no gana ningún punto.",
	timer_points: "Ganas $$ punto(s).",
	timer_partial: "Ganas $$ puntos, lo cual no es suficiente para validar la pregunta.",
	timer_instructions: "Tienes $$ segundos para contestar y validar.",
	score_final: "$1/$2 puntos",
	label_try: "último intento",
	label_tries: "intentos restantes",
	label_toast_forced_navigation_go_to_page: "Ir a la página",
	label_toast_forced_navigation_info_header: "No has visto todos los elementos de la página actual.",
	label_toast_forced_navigation_info_body: "¿Todavía quieres ir a la página siguiente?",
	label_toast_forced_navigation_warning_header: "Los ítems no fueron consultados.",
	label_toast_forced_navigation_warning_body: "Debe haber consultado todos los elementos de la página para poder acceder a la siguiente página.",
	label_toast_forced_navigation_go_to_next_page: "Siguiente página",
	label_toast_forced_navigation_stay_on_page: "Página actual",
	btn_back_reponses: "Mis respuestas",
	btn_retry_quizz: "Reiniciar",
	label_lastattempt:"Último intento",
	label_attempts:"intentos restantes",
	choice_correct: "Correcto",
	choice_incorrect: "Incorrecto",
	choice_forgotten: "Olvidado",
	accessibility_btn_summary_title: "Resumen",
	accessibility_btn_summary_label: "Mostrar resumen",
	accessibility_btn_resources_title: "Recursos adicionales",
	accessibility_btn_resources_label:"Ver recursos",
	accessibility_progressBar_title: "Barra de progreso",
	accessibility_actionButtons_label: "Botones de acción",
	accessibility_sidebar_label:"Menú de Navegación",
	accessibility_legendAndFeedback_label:"Leyenda y comentarios",
	accessibility_legendAndFeedback_btn_label:"Expande o reduce la leyenda y los comentarios",
	accessibility_limitedTimeActivity_label:"Actividad por tiempo limitado",
	accessibility_successStatus_label:"Estado de éxito",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Respuesta correcta",
	accessibility_activity_item_label_incorrect: "Respuesta incorrecta",
	accessibility_activity_item_label_forgotten: "Respuesta olvidada",
	accessibility_activity_item_label_correction: "Corrección",
};
this.localisation_nl = {
	audioPlayer:"Geluids speler",
	audioPlayer_play:"Speel",
	audioPlayer_pause:"Pauze",
	audioPlayer_seek:"Zoekbalk",
	audioPlayer_mute:"Dempen",
	audioPlayer_unmute:"Geen dempen",
	sendDataToLMS: "De registratie van uw voortgang is bezig.",
	doNotCloseThisWindow: "Sluit dit venster niet om verlies van uw gegevens te voorkomen.",
	label_consigne_completionlibre: "Voer uw antwoorden in de in te vullen ruimtes in en klik op de knop Valideren.",
	label_consigne_completionlibre_fallback: "Voer uw antwoorden in de in te vullen spaties in en klik vervolgens op de knop Valideren.",
	label_consigne_choice: "Selecteer het juiste antwoord / de juiste antwoord (en) en klik op de knop Valideren.",
	label_consigne_choice_fallback: "Selecteer het juiste antwoord / de juiste antwoord (en) en klik op de knop Valideren.",
	label_consigne_classification: "Sleep de thumbnails naar de juiste locaties en klik op de knop Valideren.",
	label_consigne_classification_fallback: "Selecteer voor elke categorie het juiste antwoord (en) en klik vervolgens op de knop Valideren.",
	label_consigne_association: "Verbind de goede paren door op de proposities te klikken en klik vervolgens op de knop Valideren.",
	label_consigne_association_fallback: "Selecteer voor elk voorstel het juiste antwoord uit de vervolgkeuzelijst en klik vervolgens op de knop Valideren.",
	label_consigne_cercle: "Plaats een enkele cirkel om het juiste antwoord / de juiste antwoord (en) en klik op de knop Valideren.",
	label_consigne_cercle_fallback: "Selecteer het juiste antwoord (en) uit de volgende keuzes, en klik vervolgens op de knop Valideren.",
	label_consigne_derouler: "Selecteer het juiste antwoord en klik op de knop Valideren.",
	label_consigne_derouler_fallback: "Selecteer het juiste antwoord en klik op de knop Valideren.",
	label_consigne_flip_fallback: "Klik op alle elementen om hun inhoud te zien.",
	label_consigne_truefalse: "Bepaal voor elke stelling of deze waar of onwaar is.",
	label_consigne_truefalse_fallback: "Bepaal voor elke stelling of deze waar of onwaar is.",
	label_restart: "Herstarten",
	label_instructions: "Instructie",
	label_validate:"Bevestigen",
	label__restart:"Herstarten",
	label_solution:"Bekijk de oplossing",
	label_my_answers:"Mijn antwoorden",
	label_feedback:"Terugkoppeling",
	label_back_to_activity:"Terug naar activiteit",
	label_folder:"Modulebronnen",
	label_summary:"Overzicht",
	label_sono:"Deze inhoud is te horen. Schakel het geluid in en druk op Beginnen.",
    label_start:"Beginnen",
    label_analyse:"Analyseer uw voortgang, een ogenblik geduld... ",
	label_rgaa_contrast:"Hoog contrast",
	label_rgaa_accessible:"Toegankelijke versie",
	label_progress:"Progressie : ",
    aria_summary:"Open de overzicht",
    aria_resources:"Open de modulebronnen",
    aria_close_summary:"Sluit de overzicht",
    aria_close_resources:"Sluit de modulebronnen",
    aria_rgaa_contrast:"Toon contrasterende kleuren",
    aria_rgaa_contrast_normal:"Toon standaardkleuren",
    aria_rgaa_accessible:"Verander naar toegankelijke modus",
    aria_rgaa_normal:"Schakel over naar de standaardmodus",
    aria_rgaa_next:"Volgend",
    aria_rgaa_prev:"Vorig",
	message_connection_lms:"Verbinding maken met de huidige tracker...",
	message_connection_lms_unknown:"Onbekende LMS-versie.",
	message_lms_error_0:"Kan het LMS-venster niet vinden...",
	message_lms_error_1:"Kan de LMS-tracker niet initialiseren...",
	message_lms_error_2:"Kan de LMS-tracker niet initialiseren...",
	message_lms_error_3:"Fout tijdens communicatie met de tracker. De sessie wordt niet opgeslagen !",
	message_lms_error_4:"Opslaggrootte voor SCORM 1.2-berichten bereikt, niet in staat om extra informatie op te slaan.",
	message_lms_error_5_syfadis:"Fout tijdens het verzenden van uw gegevens, de server is niet toegankelijk.",
	message_no_lms:"Kan het LMS niet detecteren, uw voortgang wordt niet opgeslagen, wilt u doorgaan met de training?",
	timer_nopoint: "Je verdient geen punten.",
	timer_points: "Je wint $$ punt(en).",
	timer_partial: "Je verdient $$ punten, wat niet genoeg is om de vraag te valideren.",
	timer_instructions: "Je hebt $$ seconden om beantwoorden en valideren.",
	score_final: "$1/$2 points",
	label_try: "laatste poging",
	label_tries: "resterende pogingen",
	label_toast_forced_navigation_go_to_page: "Ga naar de pagina",
	label_toast_forced_navigation_info_header: "U hebt niet alle elementen van de huidige pagina gezien.",
	label_toast_forced_navigation_info_body: "Wilt u nog steeds naar de volgende pagina gaan?",
	label_toast_forced_navigation_warning_header: "Items zijn niet geraadpleegd.",
	label_toast_forced_navigation_warning_body: "U moet alle elementen van de pagina hebben geraadpleegd om de volgende pagina te kunnen bereiken.",
	label_toast_forced_navigation_go_to_next_page: "Volgende pagina",
	label_toast_forced_navigation_stay_on_page: "Huidige pagina",
	btn_back_reponses: "Mijn antwoorden",
	btn_retry_quizz: "Herstarten",
	label_lastattempt:"Laatste poging",
	label_attempts:"resterende pogingen",
	choice_correct: "Correct",
	choice_incorrect: "Niet correct",
	choice_forgotten: "Vergeten",
	accessibility_btn_summary_title: "Samenvatting",
	accessibility_btn_summary_label: "Samenvatting weergeven",
	accessibility_btn_resources_title: "Extra middelen",
	accessibility_btn_resources_label:"Bekijk bronnen",
	accessibility_progressBar_title: "Voortgangsbalk",
	accessibility_actionButtons_label: "Actieknoppen",
	accessibility_sidebar_label:"Navigatie menu",
	accessibility_legendAndFeedback_label:"Legenda en feedback",
	accessibility_legendAndFeedback_btn_label:"Legenda en feedback uitbreiden of verkleinen",
	accessibility_limitedTimeActivity_label:"Tijdelijke activiteit",
	accessibility_successStatus_label:"Successtatus",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Goed antwoord",
	accessibility_activity_item_label_incorrect: "Fout antwoord",
	accessibility_activity_item_label_forgotten: "Vergeten reactie",
	accessibility_activity_item_label_correction: "Correctie",
};
this.localisation_de = {
	audioPlayer:"Musikplayer",
	audioPlayer_play:"Abspielen",
	audioPlayer_pause:"Pause",
	audioPlayer_seek:"Suchleiste",
	audioPlayer_mute:"Stumm",
	audioPlayer_unmute:"Stummschaltung aufheben",
	sendDataToLMS: "Die Aufzeichnung Ihres Fortschritts ist in Bearbeitung.",
	doNotCloseThisWindow: "Schließen Sie dieses Fenster nicht, um Datenverlust zu vermeiden.",
	label_consigne_completionlibre: "Geben Sie Ihre Antworten in die auszufüllenden Felder ein und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_completionlibre_fallback: "Geben Sie Ihre Antworten in die auszufüllenden Felder ein und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_choice: "Wählen Sie die richtige (n) Antwort (en) aus und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_choice_fallback: "Wählen Sie die richtige (n) Antwort (en) aus und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_classification: "Ziehen Sie die Miniaturansichten an die richtigen Stellen und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_classification_fallback: "Wählen Sie für jede Kategorie die richtige (n) Antwort (en) aus und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_association: "Verbinde die guten Paare, indem du auf die Vorschläge klickst und dann auf die Schaltfläche Validieren klickst.",
	label_consigne_association_fallback: "Wählen Sie für jeden Vorschlag die richtige Antwort aus der Dropdown-Liste aus und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_cercle: "Platziere einen einzelnen Kreis um die richtige (n) Antwort (en) und klicke dann auf die Schaltfläche Validieren.",
	label_consigne_cercle_fallback: "Wählen Sie die richtige (n) Antwort (en) aus den folgenden Auswahlmöglichkeiten aus und klicken Sie dann auf die Schaltfläche Validieren.",
	label_consigne_derouler: "Wählen Sie die richtige Antwort aus und klicken Sie auf die Schaltfläche Validieren.",
	label_consigne_derouler_fallback: "Wählen Sie die richtige Antwort aus und klicken Sie auf die Schaltfläche Validieren.",
	label_consigne_flip_fallback: "Klicken Sie auf alle Elemente, um deren Inhalt anzuzeigen.",
	label_consigne_truefalse: "Bestimmen Sie für jede Aussage, ob sie wahr oder falsch ist.",
	label_consigne_truefalse_fallback: "Bestimmen Sie für jede Aussage, ob sie wahr oder falsch ist.",
	label_restart: "Neustart",
	label_instructions: "Anleitung",
	label_validate:"Bestätigen",
	label__restart:"Neustart",
	label_solution:"Siehe die Lösung",
	label_my_answers:"Meine Antworten",
	label_feedback:"Feedback",
	label_back_to_activity:"Zurück zur Aktivität",
	label_folder:"Ressourcen",
	label_summary:"Zusammenfassung",
	label_sono:"Dieser Inhalt wird abgespielt. Schalten Sie den Ton ein und drücken Sie Starten.",
    label_start:"Starten",
    label_analyse:"Analysieren Sie Ihren Fortschritt, bitte warten Sie... ",
	label_rgaa_contrast:"Hoher Kontrast",
	label_rgaa_accessible:"Barrierefrei Version",
	label_progress:"Progression : ",
    aria_summary:"Öffnen Sie die Zusammenfassung",
    aria_resources:"Ressourcen öffnen",
    aria_close_summary:"Schließen Sie die Zusammenfassung",
    aria_close_resources:"Schließen Sie die Ressourcen",
    aria_rgaa_contrast:"Kontrastfarben anzeigen",
    aria_rgaa_contrast_normal:"Standardfarben anzeigen",
    aria_rgaa_accessible:"Wechseln Sie in den barrierefreien Modus",
    aria_rgaa_normal:"Wechseln Sie in den Standardmodus",
    aria_rgaa_next:"Folgende",
    aria_rgaa_prev:"Früher",
	message_connection_lms:"Verbindung zum aktuellen Tracker...",
	message_connection_lms_unknown:"Unbekannte LMS-Version.",
	message_lms_error_0:"Kann das LMS-Fenster nicht finden...",
	message_lms_error_1:"Der LMS-Tracker kann nicht initialisiert werden...",
	message_lms_error_2:"Der LMS-Tracker kann nicht initialisiert werden...",
	message_lms_error_3:"Fehler bei der Kommunikation mit dem Tracker. Die Sitzung wird nicht gespeichert !",
	message_lms_error_4:"Speichergröße für SCORM 1.2-Nachrichten erreicht, zusätzliche Informationen können nicht gespeichert werden.",
	message_lms_error_5_syfadis:"Fehler beim Senden Ihrer Daten, der Server ist nicht erreichbar.",
	message_no_lms:"Kann das LMS nicht erkennen, wird Ihr Fortschritt nicht gespeichert. Möchten Sie das Training fortsetzen?",
	timer_nopoint: "Sie verdienen keine Punkte.",
	timer_points: "Sie gewinnen $$ Punkte.",
	timer_partial: "Sie verdienen $$ Punkte, das reicht nicht aus, um die Frage zu validieren.",
	timer_instructions: "Sie haben $$ Sekunden Zeit, zu beantworten und zu validieren..",
	score_final: "$1/$2 punkte",
	label_try: "letzter Versuch",
	label_tries: "verbleibende Versuche",
	label_toast_forced_navigation_go_to_page: "Gehen Sie zur Seite",
	label_toast_forced_navigation_info_header: "Sie haben nicht alle Elemente der aktuellen Seite gesehen.",
	label_toast_forced_navigation_info_body: "Möchten Sie immer noch zur nächsten Seite wechseln?",
	label_toast_forced_navigation_warning_header: "Artikel wurden nicht konsultiert.",
	label_toast_forced_navigation_warning_body: "Sie müssen alle Elemente der Seite konsultiert haben, um zur nächsten Seite zu gelangen.",
	label_toast_forced_navigation_go_to_next_page: "Nächste Seite",
	label_toast_forced_navigation_stay_on_page: "Aktuelle Seite",
	btn_back_reponses: "Meine Antworten",
	btn_retry_quizz: "Neustart",
	label_lastattempt:"Letzter Versuch",
	label_attempts:"verbleibende Versuche",
	choice_correct: "Richtig",
	choice_incorrect: "Falsch",
	choice_forgotten: "Vergessene",
	accessibility_btn_summary_title: "Zusammenfassung",
	accessibility_btn_summary_label: "Zusammenfassung anzeigen",
	accessibility_btn_resources_title: "Zusätzliche Ressourcen",
	accessibility_btn_resources_label:"Ressourcen anzeigen",
	accessibility_progressBar_title: "Fortschrittsanzeige",
	accessibility_actionButtons_label: "Aktionsschaltflächen",
	accessibility_sidebar_label:"Navigationsmenü",
	accessibility_legendAndFeedback_label:"Legende und Feedback",
	accessibility_legendAndFeedback_btn_label:"Legende und Feedback erweitern oder verkleinern",
	accessibility_limitedTimeActivity_label:"Zeitlich begrenzte Aktivität",
	accessibility_successStatus_label:"Erfolgsstatus",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Korrekte Antwort",
	accessibility_activity_item_label_incorrect: "Falsche Antwort",
	accessibility_activity_item_label_forgotten: "Vergessene Antwort",
	accessibility_activity_item_label_correction: "Korrektur",
};
this.localisation_it = {
	audioPlayer:"Lettore audio",
	audioPlayer_play:"Giocare",
	audioPlayer_pause:"Pausa",
	audioPlayer_seek:"Seekbar",
	audioPlayer_mute:"Muto",
	audioPlayer_unmute:"Riattiva",
	sendDataToLMS: "La registrazione dei tuoi progressi è in corso.",
	doNotCloseThisWindow: "Non chiudere questa finestra per evitare di perdere i tuoi dati.",
	label_consigne_completionlibre: "Inserisci le tue risposte negli spazi da riempire, quindi fai clic sul pulsante Convalida.",
	label_consigne_completionlibre_fallback: "Inserisci le tue risposte negli spazi da riempire, quindi fai clic sul pulsante Convalida.",
	label_consigne_choice: "Seleziona le risposte corrette, quindi fai clic sul pulsante Convalida.",
	label_consigne_choice_fallback: "Seleziona le risposte corrette, quindi fai clic sul pulsante Convalida.",
	label_consigne_classification: "Trascina le miniature nelle posizioni corrette, quindi fai clic sul pulsante Convalida.",
	label_consigne_classification_fallback: "Per ogni categoria, seleziona le risposte corrette, quindi fai clic sul pulsante Convalida.",
	label_consigne_association: "Collega le buone coppie facendo clic sulle proposte, quindi fai clic sul pulsante Convalida.",
	label_consigne_association_fallback: "Per ogni proposta, seleziona la risposta corretta dall'elenco a discesa, quindi fai clic sul pulsante Convalida.",
	label_consigne_cercle: "Posiziona un singolo cerchio attorno alle risposte corrette, quindi fai clic sul pulsante Convalida.",
	label_consigne_cercle_fallback: "Seleziona le risposte corrette dalle seguenti scelte, quindi fai clic sul pulsante Convalida.",
	label_consigne_derouler: "Seleziona la risposta corretta, quindi fai clic sul pulsante Convalida.",
	label_consigne_derouler_fallback: "Seleziona la risposta corretta, quindi fai clic sul pulsante Convalida.",
	label_consigne_flip_fallback: "Fai clic su tutti gli elementi per visualizzarne il contenuto.",
	label_consigne_truefalse: "Per ogni affermazione, determina se è vera o falsa.",
	label_consigne_truefalse_fallback: "Per ogni affermazione, determina se è vera o falsa.",
	label_restart: "Ricomincia",
	label_instructions: "Istruzioni",
	label_validate:"Convalidare",
	label__restart:"Ricomincia",
	label_solution:"Vedi la soluzione",
	label_my_answers:"Le mie risposte",
	label_feedback:"Risposta",
	label_back_to_activity:"Torna all'attività",
	label_folder:"Risorse",
	label_summary:"Sommario",
	label_sono:"Questo contenuto è suonato. Attiva il suono e premi Cominciare.",
    label_start:"Cominciare",
    label_analyse:"Analizzando i tuoi progressi, per favore aspetta ... ",
	label_rgaa_contrast:"Alto contrasto",
	label_rgaa_accessible:"Versione accessibile",
	label_progress:"Progressione : ",
    aria_summary:"Apri il riepilogo",
    aria_resources:"Risorse aperte",
    aria_close_summary:"Chiudi il sommario",
    aria_close_resources:"Risorse vicine",
    aria_rgaa_contrast:"Mostra colori contrastanti",
    aria_rgaa_contrast_normal:"Mostra colori standard",
    aria_rgaa_accessible:"Passare alla modalità accessibile",
    aria_rgaa_normal:"Passare alla modalità standard",
    aria_rgaa_next:"Seguente",
    aria_rgaa_prev:"Precedente",
	message_connection_lms:"Connessione al tracker corrente...",
	message_connection_lms_unknown:"Versione LMS sconosciuta.",
	message_lms_error_0:"Impossibile trovare la finestra LMS...",
	message_lms_error_1:"Impossibile inizializzare il tracker LMS...",
	message_lms_error_2:"Impossibile inizializzare il tracker LMS...",
	message_lms_error_3:"Errore durante la comunicazione con il tracker. La sessione non verrà salvata!",
	message_lms_error_4:"Taille de stockage pour les messages SCORM 1.2 atteinte, impossible de stocker des informations supplémentaires.Dimensioni di archiviazione per i messaggi SCORM 1.2 raggiunti, impossibilità di memorizzare ulteriori informazioni",
	message_lms_error_5_syfadis:"Errore durante l'invio dei dati, il server non è accessibile.",
	message_no_lms:"Impossibile rilevare l'LMS, i tuoi progressi non verranno salvati, vuoi continuare l'allenamento?",
	timer_nopoint: "Non guadagni punti.",
	timer_points: "Vinci $$ punti.",
	timer_partial: "Guadagni punti $$, che non è sufficiente per convalidare la domanda.",
	timer_instructions: "Hai $$ secondi per rispondere e convalidare.",
	score_final: "$1/$2 punti",
	label_try: "ultimo tentativo",
	label_tries: "tentativi rimanenti",
	label_toast_forced_navigation_go_to_page: "Vai alla pagina",
	label_toast_forced_navigation_info_header: "Non hai visto tutti gli elementi della pagina corrente.",
	label_toast_forced_navigation_info_body: "Vuoi ancora andare alla pagina successiva?",
	label_toast_forced_navigation_warning_header: "Gli articoli non sono stati consultati.",
	label_toast_forced_navigation_warning_body: "È necessario aver consultato tutti gli elementi della pagina per poter raggiungere la pagina seguente.",
	label_toast_forced_navigation_go_to_next_page: "Pagina successiva",
	label_toast_forced_navigation_stay_on_page: "Pagina corrente",
	btn_back_reponses: "Le mie risposte",
	btn_retry_quizz: "Ricomincia",
	label_lastattempt:"Ultimo tentativo",
	label_attempts:"tentativi rimanenti",
	choice_correct: "Corretta",
	choice_incorrect: "Scorretto",
	choice_forgotten: "Forgotten",
	accessibility_btn_summary_title: "Sommario",
	accessibility_btn_summary_label: "Mostra riepilogo",
	accessibility_btn_resources_title: "Risorse addizionali",
	accessibility_btn_resources_label:"Visualizza risorse",
	accessibility_progressBar_title: "Barra di avanzamento",
	accessibility_actionButtons_label: "Pulsanti di azione",
	accessibility_sidebar_label:"Menu di navigazione",
	accessibility_legendAndFeedback_label:"Legenda e feedback",
	accessibility_legendAndFeedback_btn_label:"Espandi o riduci la legenda e il feedback",
	accessibility_limitedTimeActivity_label:"Attività a tempo limitato",
	accessibility_successStatus_label:"Stato di successo",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Risposta corretta",
	accessibility_activity_item_label_incorrect: "Risposta sbagliata",
	accessibility_activity_item_label_forgotten: "Risposta dimenticata",
	accessibility_activity_item_label_correction: "Correzione",
};
this.localisation_zh = {
	audioPlayer:"音频播放器",
	audioPlayer_play:"玩",
	audioPlayer_pause:"暂停",
	audioPlayer_seek:"搜寻栏",
	audioPlayer_mute:"静音",
	audioPlayer_unmute:"取消静音",
	sendDataToLMS: "正在记录您的进度。",
	doNotCloseThisWindow: "不要关闭此窗口，以免丢失数据。",
	label_consigne_completionlibre: "在要填写的空格中输入答案，然后单击验证按钮。",
	label_consigne_completionlibre_fallback: "在要填写的空格中输入答案，然后单击验证按钮。",
	label_consigne_choice: "选择正确的答案，然后单击验证按钮。",
	label_consigne_choice_fallback: "选择正确的答案，然后单击验证按钮。",
	label_consigne_classification: "将缩略图拖动到正确的位置，然后单击“验证”按钮。",
	label_consigne_classification_fallback: "对于每个类别，选择正确的答案，然后单击验证按钮。",
	label_consigne_association: "通过单击命题，然后单击验证按钮来连接好配对。",
	label_consigne_association_fallback: "对于每个建议，请从下拉列表中选择正确的答案，然后单击“验证”按钮。",
	label_consigne_cercle: "在正确答案旁边放一个圆圈，然后单击“验证”按钮。",
	label_consigne_cercle_fallback: "从以下选项中选择正确的答案，然后单击“验证”按钮。",
	label_consigne_derouler: "选择正确的答案，然后单击验证按钮。",
	label_consigne_derouler_fallback: "选择正确的答案，然后单击验证按钮。",
	label_consigne_flip_fallback: "单击所有元素以查看其内容。",
	label_consigne_truefalse: "对于每个语句，确定它是对还是错。",
	label_consigne_truefalse_fallback: "对于每个语句，确定它是对还是错。",
	label_restart: "重新开始",
	label_instructions: "说明",
	label_validate:"验证",
	label__restart:"重新开始",
	label_solution:"查看解决方案",
	label_my_answers:"我的答案",
	label_feedback:"反馈",
	label_back_to_activity:"回到活动",
	label_folder:"资源",
	label_summary:"摘要",
	label_sono:"这个内容响起。 打开声音，然后按开始。",
    label_start:"启动",
    label_analyse:"分析您的进度，请稍候......",
	label_rgaa_contrast:"高对比度",
	label_rgaa_accessible:"无障碍版本",
	label_progress:"进展：",
    aria_summary:"打开摘要",
    aria_resources:"打开资源",
    aria_close_summary:"关闭摘要",
    aria_close_resources:"关闭资源",
    aria_rgaa_contrast:"显示对比色",
    aria_rgaa_contrast_normal:"显示标准颜色",
    aria_rgaa_accessible:"更改为可访问模式",
    aria_rgaa_normal:"切换到标准模式",
    aria_rgaa_next:"以下",
    aria_rgaa_prev:"前",
	message_connection_lms:"连接到跟踪器......",
	message_connection_lms_unknown:"未知的LMS版本。",
	message_lms_error_0:"找不到LMS窗口......",
	message_lms_error_1:"无法初始化LMS跟踪器...",
	message_lms_error_2:"无法初始化LMS跟踪器...",
	message_lms_error_3:"与跟踪器通信时出错。 会话将不会保存！",
	message_lms_error_4:"达到SCORM 1.2消息的存储大小，无法存储其他信息",
	message_lms_error_5_syfadis:"发送数据时出错，无法访问服务器。",
	message_no_lms:"无法检测到LMS，您的进度将无法保存，是否要继续培训？",
	timer_nopoint: "你没有获得任何积分",
	timer_points: "你赢了 $$ 积分。",
	timer_partial: "您获得了 $$ 积分，这还不足以验证问题",
	timer_instructions: "你有 $$ 秒可以回答和验证",
	score_final: "$1/$2 点",
	label_try: "最后一次尝试",
	label_tries: "剩下的尝试",
	label_toast_forced_navigation_go_to_page: "转到页面",
	label_toast_forced_navigation_info_header: "您还没有看到当前页面的所有元素。",
	label_toast_forced_navigation_info_body: "你还想进入下一页吗？",
	label_toast_forced_navigation_warning_header: "没有咨询物品。",
	label_toast_forced_navigation_warning_body: "您必须咨询页面的所有元素才能访问以下页面。",
	label_toast_forced_navigation_go_to_next_page: "下一页",
	label_toast_forced_navigation_stay_on_page: "当前页面",
	btn_back_reponses: "我的答案",
	btn_retry_quizz: "重新开始",
	label_lastattempt:"最后一次尝试",
	label_attempts:"剩下的尝试",
	choice_correct: "正确",
	choice_incorrect: "不正确",
	choice_forgotten: "忘记了",
	accessibility_btn_summary_title: "摘要",
	accessibility_btn_summary_label: "显示摘要",
	accessibility_btn_resources_title: "额外资源",
	accessibility_btn_resources_label:"查看资源",
	accessibility_progressBar_title: "进度条",
	accessibility_actionButtons_label: "动作按钮",
	accessibility_sidebar_label:"导航菜单",
	accessibility_legendAndFeedback_label:"图例和反馈",
	accessibility_legendAndFeedback_btn_label:"扩大或缩小图例和反馈",
	accessibility_limitedTimeActivity_label:"限时活动",
	accessibility_successStatus_label:"成功状态",
	accessibility_header_logo_alt: "商标",
	accessibility_activity_item_label_correct: "正确答案",
	accessibility_activity_item_label_incorrect: "不正确的答案",
	accessibility_activity_item_label_forgotten: "被遗忘的回应",
	accessibility_activity_item_label_correction: "更正",
};
this.localisation_pt = {
	audioPlayer:"Tocador de Áudio",
	audioPlayer_play:"Jogar",
	audioPlayer_pause:"Pausa",
	audioPlayer_seek:"Seekbar",
	audioPlayer_mute:"Mudo",
	audioPlayer_unmute:"Com som",
	sendDataToLMS: "A gravação de seu progresso está em andamento.",
	doNotCloseThisWindow: "Não feche esta janela para evitar a perda de seus dados.",
	label_consigne_completionlibre: "Insira suas respostas nos espaços a serem preenchidos e clique no botão Validar.",
	label_consigne_completionlibre_fallback: "Insira suas respostas nos espaços a serem preenchidos e clique no botão Validar.",
	label_consigne_choice: "Selecione a (s) resposta (s) correta (s) e clique no botão Validar.",
	label_consigne_choice_fallback: "Selecione a (s) resposta (s) correta (s) e clique no botão Validar.",
	label_consigne_classification: "Arraste as miniaturas para os locais corretos e clique no botão Validar.",
	label_consigne_classification_fallback: "Para cada categoria, selecione a (s) resposta (s) correta (s) e clique no botão Validar.",
	label_consigne_association: "Conecte os pares bons clicando nas proposições, depois clique no botão Validar.",
	label_consigne_association_fallback: "Para cada proposta, selecione a resposta correta na lista suspensa e clique no botão Validar.",
	label_consigne_cercle: "Coloque um único círculo ao redor da (s) resposta (s) correta (s) e clique no botão Validar.",
	label_consigne_cercle_fallback: "Selecione a (s) resposta (s) correta (s) entre as seguintes opções e clique no botão Validar.",
	label_consigne_derouler: "Selecione a resposta correta e clique no botão Validar.",
	label_consigne_derouler_fallback: "Selecione a resposta correta e clique no botão Validar.",
	label_consigne_flip_fallback: "Clique em todos os elementos para ver seu conteúdo.",
	label_consigne_truefalse: "Para cada afirmação, determine se é verdadeira ou falsa.",
	label_consigne_truefalse_fallback: "Para cada afirmação, determine se é verdadeira ou falsa.",
	label_restart: "Reiniciar",
	label_instructions: "Instruções",
	label_validate:"Validar",
	label__restart:"Reiniciar",
	label_solution:"Veja a solução",
	label_my_answers:"Minhas respostas",
	label_feedback:"Comentários",
	label_back_to_activity:"De volta à atividade",
	label_folder:"Recursos",
	label_summary:"Resumo",
	label_sono:"Este conteúdo é soado. Ligue o som e pressione Iniciar.",
    label_start:"Começo",
    label_analyse:"Analisando seu progresso, por favor aguarde...",
	label_rgaa_contrast:"Alto contraste",
	label_rgaa_accessible:"Versão acessível",
	label_progress:"Progressão : ",
    aria_summary:"Abra o resumo",
    aria_resources:"Recursos Abertos",
    aria_close_summary:"Feche o resumo",
    aria_close_resources:"Fechar recursos",
    aria_rgaa_contrast:"Mostrar cores contrastantes",
    aria_rgaa_contrast_normal:"Mostrar cores padrão",
    aria_rgaa_accessible:"Alterar para o modo acessível",
    aria_rgaa_normal:"Mude para o modo padrão",
    aria_rgaa_next:"Seguinte",
    aria_rgaa_prev:"Anterior",
	message_connection_lms:"Conectando-se ao rastreador ...",
	message_connection_lms_unknown:"Versão desconhecida do LMS.",
	message_lms_error_0:"Não é possível encontrar a janela do LMS...",
	message_lms_error_1:"Não é possível inicializar o rastreador LMS...",
	message_lms_error_2:"INão é possível inicializar o rastreador LMS...",
	message_lms_error_3:"Erro durante a comunicação com o rastreador. A sessão não será salva!",
	message_lms_error_4:"Tamanho de armazenamento para mensagens SCORM 1.2 atingidas, incapaz de armazenar informações adicionais",
	message_lms_error_5_syfadis:"Erro ao enviar seus dados, o servidor não está acessível.",
	message_no_lms:"Não é possível detectar o LMS, seu progresso não será salvo, você deseja continuar o treinamento?",
	timer_nopoint: "Você não ganha pontos.",
	timer_points: "Você ganha $$ ponto(s).",
	timer_partial: "Você ganha $$ pontos, o que não é suficiente para validar a questão.",
	timer_instructions: "Você tem $$ segundos para responder e validar.",
	score_final: "$1/$2 pontos",
	label_try: "última tentativa",
	label_tries: "tentativas restantes",
	label_toast_forced_navigation_go_to_page: "Vá para a página",
	label_toast_forced_navigation_info_header: "Você não viu todos os elementos da página atual.",
	label_toast_forced_navigation_info_body: "Você ainda quer ir para a próxima página?",
	label_toast_forced_navigation_warning_header: "Itens não foram consultados.",
	label_toast_forced_navigation_warning_body: "Você deve ter consultado todos os elementos da página para poder acessar a seguinte página.",
	label_toast_forced_navigation_go_to_next_page: "Próxima página",
	label_toast_forced_navigation_stay_on_page: "Pagina atual",
	btn_back_reponses: "Minhas respostas",
	btn_retry_quizz: "Reiniciar",
	label_lastattempt:"Última tentativa",
	label_attempts:"tentativas restantes",
	choice_correct: "Corrigir",
	choice_incorrect: "Incorreta",
	choice_forgotten: "Esquecido",
	accessibility_btn_summary_title: "Resumo",
	accessibility_btn_summary_label: "Mostrar resumo",
	accessibility_btn_resources_title: "Recursos adicionais",
	accessibility_btn_resources_label:"Ver recursos",
	accessibility_progressBar_title: "Barra de progresso",
	accessibility_actionButtons_label: "Botões de ação",
	accessibility_sidebar_label:"Menu de navegação",
	accessibility_legendAndFeedback_label:"Legenda e feedback",
	accessibility_legendAndFeedback_btn_label:"Expandir ou diminuir legenda e feedback",
	accessibility_limitedTimeActivity_label:"Atividade por tempo limitado",
	accessibility_successStatus_label:"Status de sucesso",
	accessibility_header_logo_alt: "Logotipo",
	accessibility_activity_item_label_correct: "Resposta correta",
	accessibility_activity_item_label_incorrect: "Resposta incorreta",
	accessibility_activity_item_label_forgotten: "Resposta esquecida",
	accessibility_activity_item_label_correction: "Correção",
};
this.localisation_tr = {
	audioPlayer:"Ses oynatıcı",
	audioPlayer_play:"Oyna",
	audioPlayer_pause:"Duraklat",
	audioPlayer_seek:"Arama çubuğu",
	audioPlayer_mute:"Sessiz",
	audioPlayer_unmute:"Sesi Aç",
	sendDataToLMS: "İlerlemenizin kaydı devam ediyor.",
	doNotCloseThisWindow: "Verilerinizi kaybetmemek için bu pencereyi kapatmayın.",
	label_consigne_completionlibre: "Cevaplarınızı doldurulacak boşluklara girin ve ardından Doğrula butonuna tıklayın.",
	label_consigne_completionlibre_fallback: "Cevaplarınızı doldurulacak boşluklara girin ve ardından Doğrula düğmesine tıklayın.",
	label_consigne_choice: "Doğru cevapları seçin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_choice_fallback: "Doğru cevapları seçin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_classification: "Küçük resimleri doğru konumlara sürükleyin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_classification_fallback: "Her kategori için doğru cevapları seçin ve ardından Doğrula düğmesine tıklayın.",
	label_consigne_association: "Tekliflere tıklayarak iyi çiftleri bağlayın ve ardından Doğrula düğmesine tıklayın.",
	label_consigne_association_fallback: "Her teklif için, açılır listeden doğru cevabı seçin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_cercle: "Doğru cevapların etrafına tek bir daire yerleştirin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_cercle_fallback: "Aşağıdaki seçeneklerden doğru yanıtları seçin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_derouler: "Doğru cevabı seçin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_derouler_fallback: "Doğru cevabı seçin ve ardından Doğrula düğmesini tıklayın.",
	label_consigne_flip_fallback: "İçeriklerini görmek için tüm öğelere tıklayın.",
	label_consigne_truefalse: "Her ifade için doğru mu yanlış mı olduğunu belirleyin.",
	label_consigne_truefalse_fallback: "Her ifade için doğru mu yanlış mı olduğunu belirleyin.",
	label_restart: "Tekrar başlat",
	label_instructions: "Talimatlar",
	label_validate:"Onaylamak",
	label__restart:"Tekrar başlat",
	label_solution:"Çözüme bakın",
	label_my_answers:"Benim cevaplarım",
	label_feedback:"Geri bildirim",
	label_back_to_activity:"Etkinliğe geri dön",
	label_folder:"Kaynaklar",
	label_summary:"Özet",
	label_sono:"Bu içerik geliyor. Sesi açın ve Başlat'a basın.",
    label_start:"Başlangıç",
    label_analyse:"İlerlemenizi analiz ediyor, lütfen bekleyin ... ",
	label_rgaa_contrast:"Yüksek kontrast",
	label_rgaa_accessible:"Erişilebilir versiyon",
	label_progress:"İlerleme : ",
    aria_summary:"Özeti aç",
    aria_resources:"Kaynakları aç",
    aria_close_summary:"Özeti kapatın",
    aria_close_resources:"Kaynakları kapat",
    aria_rgaa_contrast:"Kontrast renkler göster",
    aria_rgaa_contrast_normal:"Standart renkleri göster",
    aria_rgaa_accessible:"Erişilebilir moda geç",
    aria_rgaa_normal:"Standart moda geç",
    aria_rgaa_next:"Sonraki",
    aria_rgaa_prev:"Önceki",
	message_connection_lms:"İzleyiciye bağlanıyor...",
	message_connection_lms_unknown:"Bilinmeyen LMS sürümü.",
	message_lms_error_0:"LMS penceresi bulunamıyor...",
	message_lms_error_1:"LMS izleyici başlatılamıyor...",
	message_lms_error_2:"LMS izleyici başlatılamıyor...",
	message_lms_error_3:"İzleyiciyle iletişim sırasında hata oluştu. Oturum kaydedilmeyecek!",
	message_lms_error_4:"SCORM 1.2 mesajları için depolama boyutuna ulaşıldı, ek bilgi depolanamadı",
	message_lms_error_5_syfadis:"Verilerinizi gönderirken hata oluştu, sunucuya erişilemiyor.",
	message_no_lms:"LMS tespit edilemiyor, gelişiminiz kaydedilmeyecek, eğitime devam etmek istiyor musunuz?",
	timer_nopoint: "Hiç puan kazanmıyorsun.",
	timer_points: "$$ puan kazandınız.",
	timer_partial: "$$ puan kazanırsınız, soruyu doğrulamak için yeterli değil.",
	timer_instructions: "Cevaplamak ve onaylamak için $$ saniyeniz var.",
	score_final: "$1/$2 makas",
	label_try: "son deneme",
	label_tries: "kalan denemeler",
	label_toast_forced_navigation_go_to_page: "Sayfaya git",
	label_toast_forced_navigation_info_header: "Geçerli sayfanın tüm öğelerini görmediniz.",
	label_toast_forced_navigation_info_body: "Hala bir sonraki sayfaya gitmek istiyor musun?",
	label_toast_forced_navigation_warning_header: "Öğelere danışılmadı.",
	label_toast_forced_navigation_warning_body: "Bir sonraki sayfaya ulaşmak için sayfanın tüm elemanlarına başvurmuş olmalısınız.",
	label_toast_forced_navigation_go_to_next_page: "Sonraki Sayfa",
	label_toast_forced_navigation_stay_on_page: "Geçerli sayfa",
	btn_back_reponses: "Benim cevaplarım",
	btn_retry_quizz: "Tekrar başlat",
	label_lastattempt:"Son deneme",
	label_attempts:"kalan girişimler",
	choice_correct: "Doğru",
	choice_incorrect: "Yanlış",
	choice_forgotten: "Unutulmuş",
	accessibility_btn_summary_title: "Özet",
	accessibility_btn_summary_label: "Özeti göster",
	accessibility_btn_resources_title: "Ek kaynaklar",
	accessibility_btn_resources_label:"Kaynakları görüntüleme",
	accessibility_progressBar_title: "İlerleme çubuğu",
	accessibility_actionButtons_label: "İşlem düğmeleri",
	accessibility_sidebar_label:"Gezinme menüsü",
	accessibility_legendAndFeedback_label:"Açıklama ve geri bildirim",
	accessibility_legendAndFeedback_btn_label:"Göstergeyi ve geri bildirimi genişletme veya daraltma",
	accessibility_limitedTimeActivity_label:"Sınırlı zaman etkinliği",
	accessibility_successStatus_label:"Başarı durumu",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Doğru cevap",
	accessibility_activity_item_label_incorrect: "Yanlış cevap",
	accessibility_activity_item_label_forgotten: "Unutulmuş yanıt",
	accessibility_activity_item_label_correction: "Düzeltme",
};
this.localisation_el = {
	audioPlayer:"Αναπαραγωγή ήχου",
	audioPlayer_play:"Παίζω",
	audioPlayer_pause:"Παύση",
	audioPlayer_seek:"μπαρα αναζήτησης",
	audioPlayer_mute:"Βουβός",
	audioPlayer_unmute:"Σίγαση",
	sendDataToLMS: "Η καταγραφή της προόδου σας βρίσκεται σε εξέλιξη.",
	doNotCloseThisWindow: "Μην κλείσετε αυτό το παράθυρο για να αποφύγετε την απώλεια των δεδομένων σας.",
	label_consigne_completionlibre: "Εισαγάγετε τις απαντήσεις σας στα κενά προς συμπλήρωση και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_completionlibre_fallback: "Εισαγάγετε τις απαντήσεις σας στα κενά προς συμπλήρωση και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_choice: "Επιλέξτε τις σωστές απαντήσεις και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_choice_fallback: "Επιλέξτε τις σωστές απαντήσεις και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_classification: "Σύρετε τις μικρογραφίες στις σωστές τοποθεσίες και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_classification_fallback: "Για κάθε κατηγορία, επιλέξτε τις σωστές απαντήσεις και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_association: "Συνδέστε τα καλά ζεύγη κάνοντας κλικ στις προτάσεις και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_association_fallback: "Για κάθε πρόταση, επιλέξτε τη σωστή απάντηση από την αναπτυσσόμενη λίστα και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_cercle: "Τοποθετήστε έναν μόνο κύκλο γύρω από τις σωστές απαντήσεις και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_cercle_fallback: "Επιλέξτε τις σωστές απαντήσεις από τις ακόλουθες επιλογές και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_derouler: "Επιλέξτε τη σωστή απάντηση και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_derouler_fallback: "Επιλέξτε τη σωστή απάντηση και, στη συνέχεια, κάντε κλικ στο κουμπί Επικύρωση.",
	label_consigne_flip_fallback: "Κάντε κλικ σε όλα τα στοιχεία για να δείτε το περιεχόμενό τους.",
	label_consigne_truefalse: "Για κάθε δήλωση, προσδιορίστε εάν είναι αληθής ή ψευδής.",
	label_consigne_truefalse_fallback: "Για κάθε δήλωση, προσδιορίστε εάν είναι αληθής ή ψευδής.",
	label_restart: "επανεκκίνηση",
	label_instructions: "Οδηγίες",
	label_validate:"Επικυρώνω",
	label__restart:"Επανεκκίνηση",
	label_solution:"Δείτε τη λύση",
	label_my_answers:"Οι απαντήσεις μου",
	label_feedback:"Ανατροφοδότηση",
	label_back_to_activity:"Επιστροφή στη δραστηριότητα",
	label_folder:"Πόροι",
	label_summary:"Περίληψη",
	label_sono:"Αυτό το περιεχόμενο ακούγεται. Ενεργοποιήστε τον ήχο και πατήστε Έναρξη.",
    label_start:"Έναρξη.",
    label_analyse:"Αναλύοντας την πρόοδό σας, παρακαλώ περιμένετε...",
	label_rgaa_contrast:"Υψηλή αντίθεση",
	label_rgaa_accessible:"Προσβάσιμη έκδοση",
	label_progress:"Εξέλιξη : ",
    aria_summary:"Ανοίξτε τη σύνοψη",
    aria_resources:"Άνοιγμα πόρων",
    aria_close_summary:"Κλείστε τη σύνοψη",
    aria_close_resources:"Κλείσιμο πόρων",
    aria_rgaa_contrast:"Εμφάνιση χρωματικών αντιθέσεων",
    aria_rgaa_contrast_normal:"Εμφάνιση τυπικών χρωμάτων",
    aria_rgaa_accessible:"Αλλαγή σε προσπελάσιμη λειτουργία",
    aria_rgaa_normal:"Αλλαγή σε κανονική λειτουργία",
    aria_rgaa_next:"Επόμενο",
    aria_rgaa_prev:"Προηγούμενες",
	message_connection_lms:"Σύνδεση με τον τρέχοντα ιχνηλάτη...",
	message_connection_lms_unknown:"Άγνωστη έκδοση LMS.",
	message_lms_error_0:"Δεν είναι δυνατή η εύρεση του παραθύρου LMS...",
	message_lms_error_1:"Δεν ήταν δυνατή η προετοιμασία του εργαλείου παρακολούθησης LMS...",
	message_lms_error_2:"Δεν ήταν δυνατή η προετοιμασία του εργαλείου παρακολούθησης LMS...",
	message_lms_error_3:"Σφάλμα κατά την επικοινωνία με τον ιχνηλάτη. Η συνεδρία δεν θα αποθηκευτεί!",
	message_lms_error_4:"Μέγεθος αποθήκευσης για SCORM 1,2 μηνύματα που έχουν επιτευχθεί, δεν είναι δυνατή η αποθήκευση πρόσθετων πληροφοριών.",
	message_lms_error_5_syfadis:"Σφάλμα κατά την αποστολή των δεδομένων σας, ο διακομιστής δεν είναι προσβάσιμος.",
	message_no_lms:"Δεν είναι δυνατή η ανίχνευση του LMS, η πρόοδό σας δεν θα αποθηκευτεί, θέλετε να συνεχίσετε την εκπαίδευση;",
	timer_nopoint: "Δεν κερδίζετε πόντους.",
	timer_points: "Κερδίζετε πόντους $$.",
	timer_partial: "Κερδίζετε πόντους $$, πράγμα που δεν αρκεί για την επικύρωση της ερώτησης.",
	timer_instructions: "Έχετε $$ δευτερόλεπτα για να απαντήσετε και να επικυρώσετε.",
	score_final: "$1/$2 σημεία",
	label_try: "τελευταία προσπάθεια",
	label_tries: "υπόλοιπες προσπάθειες",
	label_toast_forced_navigation_go_to_page: "Μεταβείτε στη σελίδα",
	label_toast_forced_navigation_info_header: "Δεν έχετε δει όλα τα στοιχεία της τρέχουσας σελίδας.",
	label_toast_forced_navigation_info_body: "Θέλετε ακόμα να πάτε στην επόμενη σελίδα;",
	label_toast_forced_navigation_warning_header: "Τα στοιχεία δεν ζητήθηκαν.",
	label_toast_forced_navigation_warning_body: "Πρέπει να έχετε συμβουλευτεί όλα τα στοιχεία της σελίδας για να μπορέσετε να φτάσετε στην επόμενη σελίδα.",
	label_toast_forced_navigation_go_to_next_page: "Επόμενη σελίδα",
	label_toast_forced_navigation_stay_on_page: "Τρέχουσα σελίδα",
	btn_back_reponses: "Οι απαντήσεις μου",
	btn_retry_quizz: "Επανεκκίνηση",
	label_lastattempt:"Τελευταία προσπάθεια",
	label_attempts:"υπόλοιπες προσπάθειες",
	choice_correct: "Σωστός",
	choice_incorrect: "Ανακριβής",
	choice_forgotten: "Ξεχασμένος",
	accessibility_btn_summary_title: "Περίληψη",
	accessibility_btn_summary_label: "Εμφάνιση περίληψης",
	accessibility_btn_resources_title: "Επιπρόσθετοι πόροι",
	accessibility_btn_resources_label:"Προβολή πόρων",
	accessibility_progressBar_title: "Γραμμή προόδου",
	accessibility_actionButtons_label: "Κουμπιά δράσης",
	accessibility_sidebar_label:"Μενού πλοήγησης",
	accessibility_legendAndFeedback_label:"Θρύλος και σχόλια",
	accessibility_legendAndFeedback_btn_label:"Αναπτύξτε ή συρρικνώστε το μύθο και τα σχόλια",
	accessibility_limitedTimeActivity_label:"Δραστηριότητα περιορισμένου χρόνου",
	accessibility_successStatus_label:"Κατάσταση επιτυχίας",
	accessibility_header_logo_alt: "λογότυπο",
	accessibility_activity_item_label_correct: "Σωστή απάντηση",
	accessibility_activity_item_label_incorrect: "Λανθασμένη απάντηση",
	accessibility_activity_item_label_forgotten: "Ξεχασμένη απάντηση",
	accessibility_activity_item_label_correction: "Διόρθωση",
};
this.localisation_ar = {
	audioPlayer:"مشغل الصوت",
	audioPlayer_play:"لعب",
	audioPlayer_pause:"وقفة",
	audioPlayer_seek:"شريط البحث",
	audioPlayer_mute:"كتم الصوت",
	audioPlayer_unmute:"إعادة الصوت",
	sendDataToLMS: "تسجيل تقدمك قيد التقدم.",
	doNotCloseThisWindow: "لا تغلق هذه النافذة لتجنب فقدان بياناتك.",
	label_consigne_completionlibre: "أدخل إجاباتك في الفراغات المراد ملؤها ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_completionlibre_fallback: "أدخل إجاباتك في الفراغات المراد ملؤها ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_choice: "حدد الإجابة (الإجابات) الصحيحة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_choice_fallback: "حدد الإجابة (الإجابات) الصحيحة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_classification: "اسحب الصور المصغرة إلى المواقع الصحيحة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_classification_fallback: "لكل فئة ، حدد الإجابة (الإجابات) الصحيحة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_association: "قم بتوصيل الأزواج الجيدة بالنقر فوق الاقتراحات ، ثم انقر فوق الزر التحقق من الصحة.",
	label_consigne_association_fallback: "لكل اقتراح ، حدد الإجابة الصحيحة من القائمة المنسدلة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_cercle: "ضع دائرة واحدة حول الإجابة (الإجابات) الصحيحة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_cercle_fallback: "حدد الإجابة (الإجابات) الصحيحة من الخيارات التالية ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_derouler: "حدد الإجابة الصحيحة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_derouler_fallback: "حدد الإجابة الصحيحة ، ثم انقر على زر التحقق من الصحة.",
	label_consigne_flip_fallback: "انقر على جميع العناصر لرؤية محتواها.",
	label_consigne_truefalse: "لكل عبارة ، حدد ما إذا كانت صحيحة أم خاطئة.",
	label_consigne_truefalse_fallback: "لكل عبارة ، حدد ما إذا كانت صحيحة أم خاطئة.",
	label_restart: "إعادة بدء",
	label_instructions: "تعليمات",
	label_validate:"التحقق من صحة",
	label__restart:"إعادة بدء",
	label_solution:"انظر الحل",
	label_my_answers:"اجاباتي",
	label_feedback:"ردود الفعل",
	label_back_to_activity:"العودة إلى النشاط",
	label_folder:"موارد",
	label_summary:"فهرس",
	label_sono:"بدا هذا المحتوى. قم بتشغيل الصوت واضغط على ابدأ.",
    label_start:"بداية",
    label_analyse:"تحليل التقدم المحرز الخاص بك ، يرجى الانتظار ...",
	label_rgaa_contrast:"التباين العالي",
	label_rgaa_accessible:"نسخة يمكن الوصول إليها",
	label_progress:"التقدم : ",
    aria_summary:"افتح الملخص",
    aria_resources:"المصادر المفتوحة",
    aria_close_summary:"أغلق الملخص",
    aria_close_resources:"أغلق الموارد",
    aria_rgaa_contrast:"إظهار الألوان المتناقضة",
    aria_rgaa_contrast_normal:"عرض الألوان القياسية",
    aria_rgaa_accessible:"التغيير إلى وضع الوصول إليها",
    aria_rgaa_normal:"التغيير إلى الوضع القياسي",
    aria_rgaa_next:"التالي",
    aria_rgaa_prev:"سابق",
	message_connection_lms:"جارٍ الاتصال بـ تعقب ...",
	message_connection_lms_unknown:"إصدار LMS غير معروف.",
	message_lms_error_0:"لا يمكن العثور على نافذة LMS ...",
	message_lms_error_1:"لا يمكن تهيئة متعقب LMS ...",
	message_lms_error_2:"لا يمكن تهيئة متعقب LMS ...",
	message_lms_error_3:"خطأ أثناء الاتصال مع تعقب. لن يتم حفظ الجلسة!",
	message_lms_error_4:"تم الوصول إلى حجم التخزين لرسائل SCORM 1.2 ، غير قادر على تخزين معلومات إضافية",
	message_lms_error_5_syfadis:"خطأ أثناء إرسال بياناتك ، لا يمكن الوصول إلى الخادم.",
	message_no_lms:"غير قادر على اكتشاف LMS ، لن يتم حفظ تقدمك ، هل ترغب في مواصلة التدريب؟",
	timer_nopoint: "أنت لا تفوز بالنقاط.",
	timer_points: "تكسب نقطة $$. ",
	timer_partial: "تكسب نقطة $$ ، وهذا لا يكفي للتحقق من صحة السؤال.",
	timer_instructions: "لديك $$ ثواني للإجابة والتحقق من صحتها.",
	score_final: "$1/$2 نقاط",
	label_try: "أخر محاولة",
	label_tries: "يحاول المتبقية",
	label_toast_forced_navigation_go_to_page: "انتقل إلى الصفحة",
	label_toast_forced_navigation_info_header: "لم تشاهد جميع عناصر الصفحة الحالية.",
	label_toast_forced_navigation_info_body: "هل ما زلت تريد الذهاب إلى الصفحة التالية؟",
	label_toast_forced_navigation_warning_header: "لم يتم التشاور البنود.",
	label_toast_forced_navigation_warning_body: "يجب أن تستشير جميع عناصر الصفحة حتى تتمكن من الوصول إلى الصفحة التالية.",
	label_toast_forced_navigation_go_to_next_page: "الصفحة التالية",
	label_toast_forced_navigation_stay_on_page: "الصفحه الحاليه",
	btn_back_reponses: "اجاباتي",
	btn_retry_quizz: "إعادة بدء",
	label_lastattempt:"المحاولة الأخيرة",
	label_attempts:"المحاولات المتبقية",
	choice_correct: "صيح",
	choice_incorrect: "غير صحيح",
	choice_forgotten: "نسي",
	accessibility_btn_summary_title: "ملخص",
	accessibility_btn_summary_label: "إظهار الملخص",
	accessibility_btn_resources_title: "مصادر إضافية",
	accessibility_btn_resources_label:"عرض الموارد",
	accessibility_progressBar_title: "شريط التقدم",
	accessibility_actionButtons_label: "أزرار الإجراءات",
	accessibility_sidebar_label:"قائمة الإبحار",
	accessibility_legendAndFeedback_label:"الأسطورة وردود الفعل",
	accessibility_legendAndFeedback_btn_label:"توسيع أو تقليص وسيلة الإيضاح والملاحظات",
	accessibility_limitedTimeActivity_label:"نشاط محدود الوقت",
	accessibility_successStatus_label:"حالة النجاح",
	accessibility_header_logo_alt: "شعار",
	accessibility_activity_item_label_correct: "اجابة صحيحة",
	accessibility_activity_item_label_incorrect: "إجابة خاطئة",
	accessibility_activity_item_label_forgotten: "استجابة منسية",
	accessibility_activity_item_label_correction: "تصحيح",
};
this.localisation_he = {
	audioPlayer:"נגן אודיו",
	audioPlayer_play:"לְשַׂחֵק",
	audioPlayer_pause:"הַפסָקָה",
	audioPlayer_seek:"סרגל חיפוש",
	audioPlayer_mute:"לְהַשְׁתִיק",
	audioPlayer_unmute:"בטל השתקה",
	sendDataToLMS: "הקלטת ההתקדמות שלך בעיצומה.",
	doNotCloseThisWindow: "אל תסגור חלון זה כדי להימנע מאיבוד הנתונים שלך.",
	label_consigne_completionlibre: "הזן את התשובות שלך ברווחים שיש למלא, ואז לחץ על כפתור אמת.",
	label_consigne_completionlibre_fallback: "הזן את התשובות שלך ברווחים שיש למלא, ואז לחץ על כפתור אמת.",
	label_consigne_choice: "בחר את התשובות הנכונות ולחץ על הלחצן אמת.",
	label_consigne_choice_fallback: "בחר את התשובות הנכונות ולחץ על כפתור האמת.",
	label_consigne_classification: "גרור את התמונות הממוזערות למיקומים הנכונים, ואז לחץ על הלחצן אמת.",
	label_consigne_classification_fallback: "עבור כל קטגוריה בחר בתשובות הנכונות ולחץ על כפתור אמת.",
	label_consigne_association: "חבר את הזוגות הטובים על ידי לחיצה על ההצעות, ואז לחץ על כפתור האמת.",
	label_consigne_association_fallback: "עבור כל הצעה, בחר את התשובה הנכונה מהרשימה הנפתחת, ואז לחץ על כפתור אמת.",
	label_consigne_cercle: "מקם עיגול יחיד סביב התשובות הנכונות, ואז לחץ על כפתור האימות.",
	label_consigne_cercle_fallback: "בחר את התשובות הנכונות מתוך האפשרויות הבאות, ואז לחץ על כפתור אמת.",
	label_consigne_derouler: "בחר את התשובה הנכונה, ואז לחץ על כפתור אמת.",
	label_consigne_derouler_fallback: "בחר את התשובה הנכונה, ואז לחץ על הלחצן אמת.",
	label_consigne_flip_fallback: "לחץ על כל האלמנטים כדי לראות את התוכן שלהם.",
	label_consigne_truefalse: "עבור כל הצהרה, קבע אם היא נכונה או לא נכונה.",
	label_consigne_truefalse_fallback: "עבור כל הצהרה, קבע אם היא נכונה או לא נכונה.",
	label_restart: "נסה שוב",
	label_instructions: "הוראות",
	label_validate: "לְאַמֵת",
	label__restart: "אתחול",
	label_solution: "ראה את הפיתרון",
	label_my_answers: "התשובות שלי",
	label_feedback: "מָשׁוֹב",
	label_back_to_activity: "חזרה לפעילות",
	label_folder: "אֶמְצָעִי",
	label_summary: "סיכום",
	label_sono: "לתוכן זה יש צלילים או קולות. אנא הפעל את הרמקולים שלך ללחוץ על התחל.",
	label_start: "הַתחָלָה",
	label_analyse: "ניתוח ההתקדמות שלך, אנא המתן ...",
	label_rgaa_contrast: "ניגודיות גבוה",
	label_rgaa_accessible: "גרסה נגישה",
	label_progress: "התקדמות : ",
	aria_summary: "סיכום פתוח",
	aria_resources: "משאבים פתוחים",
	aria_close_summary: "סיכום קרוב",
	aria_close_resources: "סגור משאבים",
	aria_rgaa_contrast: "מעבר לצבעים מנוגדים",
	aria_rgaa_contrast_normal: "מעבר לצבעים קלאסיים",
	aria_rgaa_accessible: "מעבר למצב נגיש",
	aria_rgaa_normal: "מעבר למצב רגיל",
	aria_rgaa_next: "הַבָּא",
	aria_rgaa_prev: "קודם",
	message_connection_lms: "התחברות ל- LMS ...",
	message_connection_lms_unknown: "גרסת LMS לא ידועה.",
	message_lms_error_0: "לא ניתן למצוא את חלון LMS ...",
	message_lms_error_1: "לא ניתן לאתחל את ה- LMS ...",
	message_lms_error_2: "לא ניתן לאתחל את ה- LMS ...",
	message_lms_error_3: "שגיאה בעת שליחת נתונים ל- LMS. ההפעלה שלך לא תישמר.",
	message_lms_error_4: "גודל האחסון של הודעות SCORM 1.2 הגיע, בלתי אפשרי לאחסן מידע נוסף",
	message_lms_error_5_syfadis: "שגיאה בעת שליחת הנתונים שלך. לא ניתן להגיע לשרת.",
	message_no_lms: "לא ניתן לאתר את ה- LMS. ההתקדמות שלך לא תישמר, האם תמשיך?",
	timer_nopoint: "אתה לא מרוויח נקודות.",
	timer_points: "אתה זוכה בנקודות $$.",
	timer_partial: "אתה מרוויח נקודות $$, וזה לא מספיק כדי לאמת את השאלה.",
	timer_instructions: "יש לך $$ שניות לענות ולאמת.",
	score_final: "$ 1 / $ 2 נקודות",
	label_try: "ניסיון אחרון",
	label_tries: "ניסיונות שנותרו",
	label_toast_forced_navigation_go_to_page: "עבור לדף",
	label_toast_forced_navigation_info_header: "לא ראית את כל המרכיבים של הדף הנוכחי.",
	label_toast_forced_navigation_info_body: "האם אתה עדיין רוצה לעבור לדף הבא?",
	label_toast_forced_navigation_warning_header: "לא נועצו בפריטים.",
	label_toast_forced_navigation_warning_body: "בטח התייעץ עם כל מרכיבי הדף בכדי שיוכלו להגיע לדף הבא.",
	label_toast_forced_navigation_go_to_next_page: "עמוד הבא",
	label_toast_forced_navigation_stay_on_page: "העמוד הנוכחי",
	btn_back_reponses: "התשובות שלי",
	btn_retry_quizz: "אתחול",
	label_lastattempt: "ניסיון אחרון",
	label_attempts: "ניסיונות שנותרו",
	choice_correct: "נכון",
	choice_incorrect: "לֹא נָכוֹן",
	choice_forgotten: "ישכח",
	accessibility_btn_summary_title: "סיכום",
	accessibility_btn_summary_label: "הצג סיכום",
	accessibility_btn_resources_title: "משאבים נוספים",
	accessibility_btn_resources_label: "הצג משאבים",
	accessibility_progressBar_title: "סרגל התקדמות",
	accessibility_actionButtons_label: "כפתורי פעולה",
	accessibility_sidebar_label: "תפריט ניווט",
	accessibility_legendAndFeedback_label:"אגדה ומשוב",
	accessibility_legendAndFeedback_btn_label: "הרחב או כיווץ אגדה ומשוב",
	accessibility_limitedTimeActivity_label: "פעילות מוגבלת בזמן",
	accessibility_successStatus_label: "סטטוס הצלחה",
	accessibility_header_logo_alt: "סֵמֶל",
	accessibility_activity_item_label_correct: "תשובה נכונה",
	accessibility_activity_item_label_incorrect: "תשובה שגויה",
	accessibility_activity_item_label_forgotten: "תגובה נשכחת",
	accessibility_activity_item_label_correction: "תיקון",
};
this.localisation_ru = {
	audioPlayer:"Аудиоплеер",
	audioPlayer_play:"Играть",
	audioPlayer_pause:"Пауза",
	audioPlayer_seek:"панель поиска",
	audioPlayer_mute:"Без звука",
	audioPlayer_unmute:"Включить звук",
	sendDataToLMS: "Идет запись вашего прогресса.",
	doNotCloseThisWindow: "Не закрывайте это окно, чтобы не потерять свои данные.",
	label_consigne_completionlibre: "Введите свои ответы в поля, которые необходимо заполнить, затем нажмите кнопку Подтвердить.",
	label_consigne_completionlibre_fallback: "Введите свои ответы в поля, которые необходимо заполнить, затем нажмите кнопку Подтвердить.",
	label_consigne_choice: "Выберите правильный ответ, затем нажмите кнопку Подтвердить.",
	label_consigne_choice_fallback: "Выберите правильный ответ (ответы), затем нажмите кнопку Подтвердить.",
	label_consigne_classification: "Перетащите эскизы в правильные места, затем нажмите кнопку Проверить.",
label_consigne_classification_fallback: "Для каждой категории выберите правильный ответ (ответы), затем нажмите кнопку Подтвердить.",
	label_consigne_association: "Подключите хорошие пары, нажав на предложения, а затем нажмите кнопку Подтвердить.",
	label_consigne_association_fallback: "Для каждого предложения выберите правильный ответ из раскрывающегося списка, затем нажмите кнопку Подтвердить.",
	label_consigne_cercle: "Обведите один кружок вокруг правильных ответов, затем нажмите кнопку Подтвердить.",
	label_consigne_cercle_fallback: "Выберите правильный ответ из следующих вариантов, затем нажмите кнопку Проверить.",
label_consigne_derouler: "Выберите правильный ответ, затем нажмите кнопку Подтвердить.",
	label_consigne_derouler_fallback: "Выберите правильный ответ, затем нажмите кнопку Подтвердить.",
	label_consigne_flip_fallback: "Щелкните все элементы, чтобы увидеть их содержимое.",
	label_consigne_truefalse: "Для каждого утверждения определите, истинно оно или ложно.",
	label_consigne_truefalse_fallback: "Для каждого утверждения определите, истинно оно или ложно.",
	label_restart: "повторная попытка",
	label_instructions: "Instructions",
	label_validate:"инструкции",
	label__restart:"Начать сначала",
	label_solution:"Посмотреть решение",
	label_my_answers:"Мои ответы",
	label_feedback:"Обратная связь",
	label_back_to_activity:"Вернуться к деятельности",
	label_folder:"Ресурсы",
	label_summary:"Резюме",
	label_sono:"Этот контент имеет звук или голоса. Пожалуйста, включите ваши динамики, нажмите кнопку Пуск.",
	label_start: "Начало",
	label_analyse:"Анализ вашего прогресса, пожалуйста, подождите ...",
	label_rgaa_contrast:"Высокий контраст",
	label_rgaa_accessible:"Доступная версия",
	label_progress:"Прогресс : ",
	aria_summary:"Открыть резюме",
	aria_resources:"Открытые ресурсы",
	aria_close_summary:"Закрыть резюме",
	aria_close_resources:"Закрыть ресурсы",
	aria_rgaa_contrast:"Переключиться на контрастные цвета",
	aria_rgaa_contrast_normal:"Переключиться на классические цвета",
	aria_rgaa_accessible:"Переключиться в доступный режим",
	aria_rgaa_normal:"Переключиться в стандартный режим",
	aria_rgaa_next:"следующий",
	aria_rgaa_prev:"предыдущий",
	message_connection_lms:"Подключение к LMS ...",
	message_connection_lms_unknown:"Неизвестная версия LMS.",
	message_lms_error_0:"Невозможно найти окно LMS ...",
	message_lms_error_1:"Невозможно инициализировать LMS ...",
	message_lms_error_2:"Невозможно инициализировать LMS ...",
	message_lms_error_3:"Ошибка при отправке данных в LMS. Ваша сессия не будет сохранена.",
	message_lms_error_4:"Достигнут размер хранилища для сообщений SCORM 1.2, невозможно хранить дополнительную информацию.",
	message_lms_error_5_syfadis:"Ошибка при отправке ваших данных. Сервер не может быть достигнут.",
	message_no_lms:"Невозможно обнаружить LMS, ваш прогресс не будет сохранен, вы продолжите?",
	timer_nopoint: "Вы не зарабатываете очки.",
	timer_points: "Вы выигрываете $$ point (s).",
	timer_partial: "Вы зарабатываете $$ баллов, что недостаточно для подтверждения вопроса.",
	timer_instructions: "У вас есть $$ секунд, чтобы ответить и подтвердить.",
	score_final: "$1 / $2 балла",
	label_try: "Последняя попытка",
	label_tries: "оставшиеся попытки",
	label_toast_forced_navigation_go_to_page: "Перейти на страницу",
	label_toast_forced_navigation_info_header: "Вы не видели все элементы текущей страницы.",
	label_toast_forced_navigation_info_body: "Вы все еще хотите перейти на следующую страницу?",
	label_toast_forced_navigation_warning_header: "Детали не были проконсультированы.",
	label_toast_forced_navigation_warning_body: "Вы должны проконсультироваться со всеми элементами страницы, чтобы перейти на следующую страницу.",
	label_toast_forced_navigation_go_to_next_page: "Следующая страница",
	label_toast_forced_navigation_stay_on_page: "Текущая страница",
	btn_back_reponses: "Мои ответы",
	btn_retry_quizz: "Начать сначала",
	label_lastattempt:"Последняя попытка",
	label_attempts:"оставшиеся попытки",
	choice_correct: "Верный",
	choice_incorrect: "некорректный",
	choice_forgotten: "забытый",
	accessibility_btn_summary_title: "Резюме",
	accessibility_btn_summary_label: "Показать резюме",
	accessibility_btn_resources_title: "Дополнительные ресурсы",
	accessibility_btn_resources_label:"Посмотреть ресурсы",
	accessibility_progressBar_title: "Индикатор",
	accessibility_actionButtons_label: "Кнопки действий",
	accessibility_sidebar_label:"Меню навигации",
	accessibility_legendAndFeedback_label:"Легенда и отзывы",
	accessibility_legendAndFeedback_btn_label:"Расширить или уменьшить легенду и обратную связь",
	accessibility_limitedTimeActivity_label:"Ограниченное время деятельности",
	accessibility_successStatus_label:"Статус успеха",
	accessibility_header_logo_alt: "логотип",
	accessibility_activity_item_label_correct: "Правильный ответ",
	accessibility_activity_item_label_incorrect: "Неправильный ответ",
	accessibility_activity_item_label_forgotten: "Забытый ответ",
	accessibility_activity_item_label_correction: "коррекция",
};
this.localisation_sk = {
	audioPlayer:"Audioprehrávač",
	audioPlayer_play:"hrať",
	audioPlayer_pause:"Pauza",
	audioPlayer_seek:"vyhľadávacia lišta",
	audioPlayer_mute:"Stíšiť",
	audioPlayer_unmute:"Zapnúť zvuk",
	sendDataToLMS: "Prebieha zaznamenávanie vášho pokroku.",
	doNotCloseThisWindow: "Nezatvárajte toto okno, aby ste nestratili svoje údaje.",
	label_consigne_completionlibre: "Zadajte svoje odpovede do polí, ktoré chcete vyplniť, a potom kliknite na tlačidlo Overiť.",
	label_consigne_completionlibre_fallback: "Zadajte svoje odpovede do polí, ktoré chcete vyplniť, a potom kliknite na tlačidlo Overiť.",
	label_consigne_choice: "Vyberte správne odpovede, potom kliknite na tlačidlo Overiť.",
	label_consigne_choice_fallback: "Vyberte správne odpovede, potom kliknite na tlačidlo Overiť.",
	label_consigne_classification: "Presuňte miniatúry na správne miesta a potom kliknite na tlačidlo Overiť.",
	label_consigne_classification_fallback: "Pre každú kategóriu vyberte správnu odpoveď (odpovede) a potom kliknite na tlačidlo Overiť.",
	label_consigne_association: "Spojte dobré páry kliknutím na propozície a potom na tlačidlo Overiť.",
	label_consigne_association_fallback: "Pre každý návrh vyberte v rozbaľovacom zozname správnu odpoveď a potom kliknite na tlačidlo Overiť.",
	label_consigne_cercle: "Umiestnite jeden kruh okolo správnych odpovedí, potom kliknite na tlačidlo Overiť.",
	label_consigne_cercle_fallback: "Vyberte správnu odpoveď z nasledujúcich možností, potom kliknite na tlačidlo Overiť.",
	label_consigne_derouler: "Vyberte správnu odpoveď a potom kliknite na tlačidlo Overiť.",
	label_consigne_derouler_fallback: "Vyberte správnu odpoveď a potom kliknite na tlačidlo Overiť.",
	label_consigne_flip_fallback: "Kliknutím na všetky prvky zobrazíte ich obsah.",
	label_consigne_truefalse: "Pri každom výroku určite, či je pravdivý alebo nepravdivý.",
	label_consigne_truefalse_fallback: "Pri každom výroku určite, či je pravdivý alebo nepravdivý.",
	label_restart: "Skúsiť znova",
	label_instructions: "Inštrukcie",
	label_validate:"Potvrdiť",
	label__restart:"Reštart",
	label_solution:"Pozrite si riešenie",
	label_my_answers:"Moje odpovede",
	label_feedback:"Spätná väzba",
	label_back_to_activity:"Späť na aktivitu",
	label_folder:"zdroje",
	label_summary:"zhrnutie",
	label_sono:"Tento obsah obsahuje zvuk alebo hlasy. Zapnite reproduktory kliknutím na tlačidlo Štart.",
	label_start: "štart",
	label_analyse:"Analýza vášho postupu, počkajte prosím ...",
	label_rgaa_contrast:"Vysoký kontrast",
	label_rgaa_accessible:"Dostupná verzia",
	label_progress:"Pokrok: ",
	aria_summary:"Otvoriť zhrnutie",
	aria_resources:"Otvorené zdroje",
	aria_close_summary:"Zavrieť zhrnutie",
	aria_close_resources:"Zatvorte zdroje",
	aria_rgaa_contrast:"Prepnite na kontrastné farby",
	aria_rgaa_contrast_normal:"Prepnite na klasické farby",
	aria_rgaa_accessible:"Prepnite do prístupného režimu",
	aria_rgaa_normal:"Prepnutie do štandardného režimu",
	aria_rgaa_next:"Ďalšie",
	aria_rgaa_prev:"predchádzajúca",
	message_connection_lms:"Pripája sa k LMS ...",
	message_connection_lms_unknown:"Neznáme verzie LMS.",
	message_lms_error_0:"Nemožno nájsť okno LMS ...",
	message_lms_error_1:"Nemožno inicializovať LMS...",
	message_lms_error_2:"Nemožno inicializovať LMS...",
	message_lms_error_3:"Chyba pri odosielaní údajov do LMS. Vaša relácia sa neuloží.",
	message_lms_error_4:"Dosiahla sa veľkosť ukladacieho priestoru pre správy SCORM 1.2, nie je možné uložiť ďalšie informácie",
	message_lms_error_5_syfadis:"Pri odosielaní údajov došlo k chybe. Server nie je dostupný.",
	message_no_lms:"Nemožno zistiť LMS, váš postup sa neuloží, pokračujete?",
	timer_nopoint: "Nezískate žiadne body.",
	timer_points: "Vyhráte $$ bod (y).",
	timer_partial: "Získate $$, čo nestačí na potvrdenie otázky.",
	timer_instructions: "Máte $$ sekúnd na odpoveď a potvrdenie.",
	score_final: "$1/$2 body",
	label_try: "posledný pokus",
	label_tries: "zostávajúce pokusy",
	label_toast_forced_navigation_go_to_page: "Prejdite na stránku",
	label_toast_forced_navigation_info_header: "Nevideli ste všetky prvky aktuálnej stránky.",
	label_toast_forced_navigation_info_body: "Naozaj chcete prejsť na ďalšiu stránku?",
	label_toast_forced_navigation_warning_header: "S položkami sa nekonzultovalo.",
	label_toast_forced_navigation_warning_body: "Aby ste sa dostali na nasledujúcu stránku, musíte navštíviť všetky prvky stránky.",
	label_toast_forced_navigation_go_to_next_page: "Ďalšia strana",
	label_toast_forced_navigation_stay_on_page: "Aktuálna stránka",
	btn_back_reponses: "Moje odpovede",
	btn_retry_quizz: "Reštart",
	label_lastattempt:"Posledný pokus",
	label_attempts:"zostávajúce pokusy",
	choice_correct: "Korektné",
	choice_incorrect: "Nesprávny",
	choice_forgotten: "Zabudnutý",
	accessibility_btn_summary_title: "Zhrnutie",
	accessibility_btn_summary_label: "Zobraziť zhrnutie",
	accessibility_btn_resources_title: "Dodatočné zdroje",
	accessibility_btn_resources_label:"Zobraziť zdroje",
	accessibility_progressBar_title: "Ukazateľ postupu",
	accessibility_actionButtons_label: "Akčné tlačidlá",
	accessibility_sidebar_label:"Navigačná ponuka",
	accessibility_legendAndFeedback_label:"Legenda a spätná väzba",
	accessibility_legendAndFeedback_btn_label:"Rozbaliť alebo zmenšiť legendu a spätnú väzbu",
	accessibility_limitedTimeActivity_label:"Časovo obmedzená aktivita",
	accessibility_successStatus_label:"Stav úspechu",
	accessibility_header_logo_alt: "Logo",
	accessibility_activity_item_label_correct: "Správna odpoveď",
	accessibility_activity_item_label_incorrect: "Nesprávna odpoveď",
	accessibility_activity_item_label_forgotten: "Zabudnutá odpoveď",
	accessibility_activity_item_label_correction: "oprava",
};